package dominio;
// Generated 06/09/2013 12:51:15 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Certificado generated by hbm2java
 */
public class Certificado  implements java.io.Serializable {


     private Integer numeroCertificado;
     private int idAhijado;
     private int idTutora;
     private int idTutor;
     private int idMadrina;
     private int idPadrino;
     private String nombreCura;
     private String libro;
     private String folio;
     private String partida;
     private Date fechaBautizmo;
     private String domicilioPadres;
     private String notasMarginales;
     private String ciudad;
     private String provincia;

    public Certificado() {
    }

    public Certificado(int idAhijado, int idTutora, int idTutor, int idMadrina, int idPadrino, String nombreCura, String libro, String folio, String partida, Date fechaBautizmo, String domicilioPadres, String notasMarginales, String ciudad, String provincia) {
       this.idAhijado = idAhijado;
       this.idTutora = idTutora;
       this.idTutor = idTutor;
       this.idMadrina = idMadrina;
       this.idPadrino = idPadrino;
       this.nombreCura = nombreCura;
       this.libro = libro;
       this.folio = folio;
       this.partida = partida;
       this.fechaBautizmo = fechaBautizmo;
       this.domicilioPadres = domicilioPadres;
       this.notasMarginales = notasMarginales;
       this.ciudad = ciudad;
       this.provincia = provincia;
    }
   
    public Integer getNumeroCertificado() {
        return this.numeroCertificado;
    }
    
    public void setNumeroCertificado(Integer numeroCertificado) {
        this.numeroCertificado = numeroCertificado;
    }
    public int getIdAhijado() {
        return this.idAhijado;
    }
    
    public void setIdAhijado(int idAhijado) {
        this.idAhijado = idAhijado;
    }
    public int getIdTutora() {
        return this.idTutora;
    }
    
    public void setIdTutora(int idTutora) {
        this.idTutora = idTutora;
    }
    public int getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(int idTutor) {
        this.idTutor = idTutor;
    }
    public int getIdMadrina() {
        return this.idMadrina;
    }
    
    public void setIdMadrina(int idMadrina) {
        this.idMadrina = idMadrina;
    }
    public int getIdPadrino() {
        return this.idPadrino;
    }
    
    public void setIdPadrino(int idPadrino) {
        this.idPadrino = idPadrino;
    }
    public String getNombreCura() {
        return this.nombreCura;
    }
    
    public void setNombreCura(String nombreCura) {
        this.nombreCura = nombreCura;
    }
    public String getLibro() {
        return this.libro;
    }
    
    public void setLibro(String libro) {
        this.libro = libro;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }
    public Date getFechaBautizmo() {
        return this.fechaBautizmo;
    }
    
    public void setFechaBautizmo(Date fechaBautizmo) {
        this.fechaBautizmo = fechaBautizmo;
    }
    public String getDomicilioPadres() {
        return this.domicilioPadres;
    }
    
    public void setDomicilioPadres(String domicilioPadres) {
        this.domicilioPadres = domicilioPadres;
    }
    public String getNotasMarginales() {
        return this.notasMarginales;
    }
    
    public void setNotasMarginales(String notasMarginales) {
        this.notasMarginales = notasMarginales;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


