package dominio;
// Generated 30/08/2013 10:17:22 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String dni;
     private String apellido;
     private String nombre;
     private String sexo;
     private Date fechaNaciemiento;
     private String lugarNacimiento;
     private String provNacimiento;
     private String nacionalidad;
     private String hijoDe;
     private String domicilio;
     private String barrio;
     private String telefonoFijo;
     private String telefonoCelular;
     private String tipoDeHijo;

    public Persona() {
    }

	
    public Persona(String dni, String apellido, String nombre, String sexo, Date fechaNaciemiento, String lugarNacimiento, String provNacimiento, String nacionalidad) {
        this.dni = dni;
        this.apellido = apellido;
        this.nombre = nombre;
        this.sexo = sexo;
        this.fechaNaciemiento = fechaNaciemiento;
        this.lugarNacimiento = lugarNacimiento;
        this.provNacimiento = provNacimiento;
        this.nacionalidad = nacionalidad;
    }
    public Persona(String dni, String apellido, String nombre, String sexo, Date fechaNaciemiento, String lugarNacimiento, String provNacimiento, String nacionalidad, String hijoDe, String domicilio, String barrio, String telefonoFijo, String telefonoCelular, String tipoDeHijo) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.sexo = sexo;
       this.fechaNaciemiento = fechaNaciemiento;
       this.lugarNacimiento = lugarNacimiento;
       this.provNacimiento = provNacimiento;
       this.nacionalidad = nacionalidad;
       this.hijoDe = hijoDe;
       this.domicilio = domicilio;
       this.barrio = barrio;
       this.telefonoFijo = telefonoFijo;
       this.telefonoCelular = telefonoCelular;
       this.tipoDeHijo = tipoDeHijo;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNaciemiento() {
        return this.fechaNaciemiento;
    }
    
    public void setFechaNaciemiento(Date fechaNaciemiento) {
        this.fechaNaciemiento = fechaNaciemiento;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public String getProvNacimiento() {
        return this.provNacimiento;
    }
    
    public void setProvNacimiento(String provNacimiento) {
        this.provNacimiento = provNacimiento;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getHijoDe() {
        return this.hijoDe;
    }
    
    public void setHijoDe(String hijoDe) {
        this.hijoDe = hijoDe;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getTipoDeHijo() {
        return this.tipoDeHijo;
    }
    
    public void setTipoDeHijo(String tipoDeHijo) {
        this.tipoDeHijo = tipoDeHijo;
    }




}


