/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.CertificadoDAO;
import dao.PersonaDAO;
import dao.imp.CertificadoDAOImp;
import dao.imp.PersonaDAOImp;
import java.awt.Color;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import modelo.Certificado;
import modelo.Persona;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import reporte.ReporteCertificadoJRDataSource;
import util.FechaUtil;



/**
 *
 * @author AnahiAramayo
 */
public class AltaCertificado extends javax.swing.JFrame {
    private Persona pCura;
    private Persona pAhijado;
    private Persona pTutor;
    private Persona pTutora;
    private Persona pPadrino;
    private Persona pMadrina;
    private String qPersona;
    private Integer idPersona;
    Persona cura;
    Persona tutor;
    Persona tutora;
    Persona padrino;
    Persona madrina;
    Persona ahijado;
    PersonaDAO personaDAO =new PersonaDAOImp();
    ArrayList<Persona> listDeCuras = new ArrayList<Persona>();
    private Certificado certificado;
    
    private boolean modificar;
    
    /**PE
     * Creates new form Inicio
     */
    public AltaCertificado() {
        initComponents();

    }
    
    
    
    public void agregar(Persona p,JTextField tipoPersona,String qPersona){
        this.qPersona = qPersona;
        //this.idPersona = idPerso;
        tipoPersona.setText(p.getApellido()+", "+p.getNombre());
        
        if ("cura".equals(qPersona)) {
            cura = p;
            this.pCura = p;
        } else {
            if ("tutor".equals(qPersona)) {
                tutor = p;
                this.pTutor = p;
            } else {
                if ("tutora".equals(qPersona)) {
                    tutora= p;
                    this.pTutora = p;
                } else {
                    if ("padrino".equals(qPersona)) {
                        padrino=p;
                        this.pPadrino = p;
                    } else {
                        if ("madrina".equals(qPersona)) {
                            madrina=p;
                            this.pMadrina = p;
                        } else {
                            ahijado=p;
                            this.pAhijado = p;
                        }
                    }
                }
            }
        }
        p = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarCertificado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombNiño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombPadre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMadre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDNINiño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDomPadres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombPadrino = new javax.swing.JTextField();
        txtNombMadrina = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtlibro = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        txtPartida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaMarginal = new javax.swing.JTextArea();
        dtchFechaBautismo = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarNiñoCertficado = new javax.swing.JButton();
        btnAgregarPadreCertficado = new javax.swing.JButton();
        btnAgregarMadreCertficado = new javax.swing.JButton();
        txtFechNacimNiño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombParroquia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarPadrinoCertficado = new javax.swing.JButton();
        btnAgregarMadrinaCertficado = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtLugarNacNiño = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtDomiParroq = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        btnAgragCura = new javax.swing.JButton();
        txtCura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Certificado");
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setOpaque(false);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(false);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar2.add(btnImprimir);

        btnCancelar.setText("Limpiar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(false);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCancelar);

        btnBuscarCertificado.setText("Buscar ");
        btnBuscarCertificado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCertificado.setOpaque(false);
        btnBuscarCertificado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCertificadoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnBuscarCertificado);

        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(10, 0, 340, 60);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos - Certificado de Bautismo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 600));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del niño:");

        txtNombNiño.setEditable(false);
        txtNombNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombNiñoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Padre:");

        txtNombPadre.setEditable(false);
        txtNombPadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Madre:");

        txtMadre.setEditable(false);
        txtMadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Provincia:");

        cmbProvincia.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jujuy", "Salta", "Tucuman", "Mendoza", "La Rioja ", "Bs As", "Santa Fe", "Cordoba", "Corrientes", "Misiones", "Entre Rios", "Tierra del Fuego", " ", " " }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("D.N.I.:");

        txtDNINiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Domicilio Padres:");

        txtDomPadres.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDomPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomPadresActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Nombre Padrino:");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Nombre Madrina:");

        txtNombPadrino.setEditable(false);
        txtNombPadrino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtNombMadrina.setEditable(false);
        txtNombMadrina.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombMadrina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombMadrinaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Libro:");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Folio:");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Partida:");

        txtlibro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtFolio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtPartida.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notas Marginales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.setOpaque(false);

        txtareaMarginal.setColumns(20);
        txtareaMarginal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtareaMarginal.setRows(5);
        jScrollPane1.setViewportView(txtareaMarginal);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Fecha del dia de bautismo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(dtchFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtchFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        btnAgregarNiñoCertficado.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregarNiñoCertficado.setText("Agregar Niño");
        btnAgregarNiñoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNiñoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarPadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregarPadreCertficado.setText("Agregar Padre");
        btnAgregarPadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadreCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregarMadreCertficado.setText("Agregar Madre");
        btnAgregarMadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadreCertficadoActionPerformed(evt);
            }
        });

        txtFechNacimNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFechNacimNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechNacimNiñoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Parroquia:");

        txtNombParroquia.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Pbro./Diacono:");

        btnAgregarPadrinoCertficado.setText("Agregar Padrino");
        btnAgregarPadrinoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadrinoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadrinaCertficado.setText("Agregar Madrina");
        btnAgregarMadrinaCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadrinaCertficadoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Lugar de Nacimiento:");

        txtLugarNacNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Ciudad:");

        cmbCiudad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "San Salvador de Jujuy", "Abra Pampa", "Abralaite", "Aguas Calientes", "Alfarcito", "Arrayanal", "Arroyo Colorado", "Bárcena", "Barrancas", "Barrios", "Bermejito", "Caimancito", "Calilegua", "Cangrejillos", "Carahunco", "Casabindo", "Casira", "Caspalá", "Catúa", "Centro Forestal", "Chalicán", "Cieneguillas", "Cochinoca", "Coctaca", "Colonia San José", "El Cóndor", "Coranzulí", "Cusi Cusi", "Don Emilio", "El Acheral", "El Aguilar", "El Angosto", "El Bananal", "El Carmen", "El Ceibal", "El Fuerte", "El Moreno", "El Piquete", "El Puesto", "El Quemado", "El Talar", "El Toro", "Fraile Pintado", "Guerrero", "Hipólito Yrigoyen", "Iturbe", "Hornaditas", "Huacalera", "Huancar", "Humahuaca", "Juella", "La Almona", "La Ciénaga", "La Esperanza", "La Intermedia", "La Manga", "La Mendieta", "La Quiaca", "Lagunillas", "León", "Libertador General San Martín", "Libertad", "Liviara", "Llulluchayoc", "Los Lapachos", "Los Manatiales", "Loteo Navea", "Lozano", "Maimará", "Mina 9 de Octubre", "Mina Pirquitas", "Miraflores", "Misa Rumi", "Monterrico", "Ocloyas", "Olaroz Chico", "Oratorio", "Paicone", "Palma Sola", "Palo Blanco", "Palpalá", "Pampa Planca", "Pampichuela", "Parapeti", "Paulina", "Perico", "Piedritas", "Puente Lavayén", "Puesto del Marqués", "Puesto Sey", "Puesto Viejo", "Pumahuasi", "Purmamarca", "Rinconada", "Rinconadilla", "Rodeíto", "Rosario del Río Grande", "San Antonio", "San Pedro", "San Francisco", "San Juan de Oros", "San Lucas", "San Pedro de Jujuy", "Santa Ana", "Santa Catalina", "Santa Clara", "Sauzal", "Susques", "Tabladitas", "Tafna", "Termas de Reyes", "Tilcara", "Tiraxi", "Tres Cruces", "Tres Pozos", "Tumbaya", "Tusaquillas", "Uquía", "Valle Colorado", "Valle Grande", "Vinalito", "Volcán", "Yala", "Yavi", "Yavi Chico", "Yoscaba", "Yuto" }));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setText("Domicilio de Parroquia:");

        txtDomiParroq.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDomiParroq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomiParroqActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setText("Barrio:");

        txtBarrio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        btnAgragCura.setText("Agregar Cura");
        btnAgragCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragCuraActionPerformed(evt);
            }
        });

        txtCura.setEditable(false);
        txtCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(txtNombParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtNombPadrino, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnAgregarPadrinoCertficado))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel19)
                .addGap(9, 9, 9)
                .addComponent(txtDomiParroq, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(txtNombMadrina, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnAgregarMadrinaCertficado))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel20)
                .addGap(16, 16, 16)
                .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel10)
                .addGap(14, 14, 14)
                .addComponent(txtCura, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAgragCura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(txtNombNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAgregarNiñoCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtDNINiño, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLugarNacNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnAgregarPadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnAgregarMadreCertficado))
                    .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtNombParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombPadrino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPadrinoCertficado))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtDomiParroq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addComponent(txtNombMadrina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMadrinaCertficado))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtCura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgragCura)
                    .addComponent(jLabel16)
                    .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNiñoCertficado)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel17)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtDNINiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(txtLugarNacNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarPadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarMadreCertficado))
                        .addGap(15, 15, 15)
                        .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane2.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 1060, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spsp2_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 1260, 880);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Abrir");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Guardar");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Guardar como");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edición");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cortar");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copiar");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Pegar");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Borrar");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Ayuda");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void btnAgregarNiñoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNiñoCertficadoActionPerformed
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        BusquedaPersona bp = new BusquedaPersona(pAhijado,this,true,txtNombNiño,"ahijado");
        bp.setVisible(true);
        //txtFechNacimNiño.setText(sdf.format(p.getFechaNaciemiento()));
        bp.setLocationRelativeTo(this);
        
        try {
            txtFechNacimNiño.setText(sdf.format(pAhijado.getFechaNaciemiento()));
            txtDNINiño.setText(pAhijado.getDni());
            //String fecha = sdf.format(p.getFechaNaciemiento());
            txtLugarNacNiño.setText(pAhijado.getLugarNacimiento());
            txtDNINiño.setText(pAhijado.getDni());            
        } catch (NullPointerException e) {
        }
        
        
//        txtNombNiño.setText(p.getApellido()+", " +p.getNombre());
//        txtNombPadre.setText(String.valueOf(p.getIdPersona()));
    }//GEN-LAST:event_btnAgregarNiñoCertficadoActionPerformed

    private void btnAgregarPadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadreCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pTutor,this,true,txtNombPadre,"tutor");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarPadreCertficadoActionPerformed

    public boolean validacion(){
        boolean vacio = true;
        ArrayList<JTextField> listaTxt = new ArrayList();
        listaTxt.add(txtNombParroquia);
        listaTxt.add(txtDomiParroq); listaTxt.add(txtBarrio);
        listaTxt.add(txtCura);listaTxt.add(txtNombNiño);
        listaTxt.add(txtFechNacimNiño);listaTxt.add(txtDNINiño);
        listaTxt.add(txtLugarNacNiño);listaTxt.add(txtNombPadre);listaTxt.add(txtMadre);
        listaTxt.add(txtDomPadres);listaTxt.add(txtNombPadrino);listaTxt.add(txtNombMadrina);
        listaTxt.add(txtlibro);listaTxt.add(txtPartida);listaTxt.add(txtFolio);
        for (Iterator<JTextField> it = listaTxt.iterator(); it.hasNext();) {
            JTextField jTextField = it.next();
            if (jTextField.getText().equals("")) {
                jTextField.setBackground(Color.red);
                vacio = true;
                break;
            }else{
                vacio = false;
            }             
        }
        return vacio;
    }
    
    private void btnAgregarMadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadreCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pTutora,this,true,txtMadre,"tutora");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarMadreCertficadoActionPerformed

    private void btnAgregarPadrinoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadrinoCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pPadrino,this,true,txtNombPadrino,"padrino");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarPadrinoCertficadoActionPerformed

    private void btnAgregarMadrinaCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadrinaCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pMadrina,this,true,txtNombMadrina,"madrina");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarMadrinaCertficadoActionPerformed

    private void txtDomiParroqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomiParroqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomiParroqActionPerformed

    private void txtDomPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomPadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomPadresActionPerformed

    private void txtNombNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombNiñoActionPerformed

    private void txtFechNacimNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechNacimNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechNacimNiñoActionPerformed

    private void txtNombMadrinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombMadrinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombMadrinaActionPerformed

    private void btnAgragCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragCuraActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pCura,this,true,txtCura,"cura");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgragCuraActionPerformed

    private void txtCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuraActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(modificar==false){
         certificado = new Certificado();
        }
        CertificadoDAO certificadoDAO = new CertificadoDAOImp();

        certificado.setNombreParroquia(txtNombParroquia.getText());
        certificado.setDomicilioParooquia(txtDomiParroq.getText());
        certificado.setBarrioParroquia(txtBarrio.getText());
        try {
            
            certificado.setIdCura(cura.getIdPersona());
            certificado.setIdAhijado(ahijado.getIdPersona());
            certificado.setIdTutor(tutor.getIdPersona());
            certificado.setIdTutora(tutora.getIdPersona());
            certificado.setIdMadrina(madrina.getIdPersona());
            certificado.setIdPadrino(padrino.getIdPersona());
//            certificado.setPersonaByIdAhijado(ahijado);
//            certificado.setPersonaByIdTutor(tutor);
//            certificado.setPersonaByIdTutora(tutora);
//            certificado.setPersonaByIdPadrino(padrino);
//            certificado.setPersonaByIdMadrina(madrina);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos...");
        }
        certificado.setDomicilioPadres(txtDomPadres.getText());
        certificado.setCiudad(cmbCiudad.getSelectedItem().toString());
        certificado.setProvincia(cmbProvincia.getSelectedItem().toString());
        certificado.setFechaBautizmo(dtchFechaBautismo.getDate());
        certificado.setLibro(txtlibro.getText());
        certificado.setPartida(txtPartida.getText());
        certificado.setFolio(txtFolio.getText());
        certificado.setNotasMarginales(txtareaMarginal.getText());

        if (validacion()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos...");
        } else {
            // se creo un certificado nuevo
            if(modificar==false){
            certificadoDAO.insert(certificado);
            }else{
                // se cargo un certificado para actualizarlo
                certificadoDAO.update(certificado);
            }
            JOptionPane.showMessageDialog(null, "Se cargo correctamente...");
            activarBotonNuevo(false);
        }
       

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       
        //        parametros.put("fechaInicio",FechaUtil.getDateDD_MM_AAAA(fechaInicio.getDate()));
        //        parametros.put("fechaFin",FechaUtil.getDateDD_MM_AAAA(fechaFin.getDate()));
       
//       String logotipo="/images/iconTecnomatica.png";
      
       //parametros de entrada
       Map parametros = new HashMap();
       String logotipo="/images/1.jpg";
//       parametros.clear();
//       parametros.put("logoParroquia", this.getClass().getResourceAsStream(logotipo));
       
       
        ReporteCertificadoJRDataSource dataSource = new ReporteCertificadoJRDataSource();
        List<Certificado> lista = new ArrayList<Certificado>();
        lista.add(certificado);
        dataSource.setListCertificado(lista);
        JasperPrint jPrintt;
        JDialog reporte = new JDialog();
        reporte.setSize(900, 700);
        reporte.setLocationRelativeTo(null);
        reporte.setModal(true);
        reporte.setTitle("INFORME");
        //  JasperReport lreporte = (JasperReport) JRLoader.loadObject("reportes/reporteAsistencia.jasper");
        try {
            // jPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reportes/reporteAsistencia.jasper"),null, new JRBeanCollectionDataSource(listaAs));
            jPrintt = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reporte/CertificadoParroquia.jasper"),(Map)parametros, dataSource);

            JRViewer jv = new JRViewer(jPrintt);
            reporte.getContentPane().add(jv);
            reporte.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarVentana();
        
        // el indicador de modificar se pne en false ya que se creara un certificado nuevo
        modificar= false;
        // inicializar los botones de opciones
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnImprimir.setEnabled(false);
        btnBuscarCertificado.setEnabled(true);
        
              
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCertificadoActionPerformed
         
       
        BusquedaCertificado bc = new BusquedaCertificado(certificado,this,true,txtNombPadrino,"padrino");
        bc.setVisible(true);
        bc.setLocationRelativeTo(this);
        
        if (bc.getCertificado().getIdAhijado()!=null) {
             // indicador de qeu se esta por cargar un certificado existente 
             modificar = true;
             // para que se pueda imprimir 
             btnImprimir.setEnabled(true);
             btnGuardar.setText("Actualizar");
             btnGuardar.setEnabled(true);
            
            //llenar todos los campos de con los datosd del certificacdo}
            certificado= bc.getCertificado();
            cura=new PersonaDAOImp().getPersona(certificado.getIdCura());
            tutor=new PersonaDAOImp().getPersona(certificado.getIdTutor());
            tutora= new PersonaDAOImp().getPersona(certificado.getIdTutora());
            padrino=new PersonaDAOImp().getPersona(certificado.getIdPadrino());
            madrina= new PersonaDAOImp().getPersona(certificado.getIdMadrina());
            ahijado= new PersonaDAOImp().getPersona(certificado.getIdAhijado());
     txtBarrio.setText(certificado.getBarrioParroquia());
     txtCura.setText(cura.getApellido()+" "+cura.getNombre());
     txtDNINiño.setText(ahijado.getDni());
     txtDomPadres.setText(certificado.getDomicilioPadres());
     txtDomiParroq.setText(certificado.getDomicilioParooquia());
     txtFechNacimNiño.setText(FechaUtil.getDateDD_MM_AAAA(ahijado.getFechaNaciemiento()));
     txtFolio.setText(certificado.getFolio());
     txtLugarNacNiño.setText(ahijado.getLugarNacimiento());
     txtMadre.setText(tutora.getApellido()+" "+tutora.getNombre());
     txtNombMadrina.setText(madrina.getApellido()+" "+madrina.getNombre());
     txtNombNiño.setText(ahijado.getApellido()+" "+ahijado.getNombre());
     txtNombPadre.setText(tutor.getApellido()+" "+tutor.getNombre() );
     txtNombPadrino.setText(padrino.getApellido()+" "+padrino.getNombre());
     txtNombParroquia.setText(certificado.getNombreParroquia());
     txtPartida.setText(certificado.getPartida());
     txtareaMarginal.setText(certificado.getNotasMarginales());
     txtlibro.setText(certificado.getLibro());
     cmbCiudad.setSelectedItem("San Salvador de Jujuy");
     cmbProvincia.setSelectedItem("Jujuy");
     dtchFechaBautismo.setDate(certificado.getFechaBautizmo());
        }
    }//GEN-LAST:event_btnBuscarCertificadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       
        limpiarVentana();
        btnNuevo.setEnabled(false);
       btnGuardar.setText("Guardar");
       btnGuardar.setEnabled(true);
       
       btnImprimir.setEnabled(false);
       btnBuscarCertificado.setEnabled(true);
       modificar= false;
    }//GEN-LAST:event_btnNuevoActionPerformed

 
 public void activarBotonNuevo(boolean b){
     btnGuardar.setEnabled(b);
     btnImprimir.setEnabled(!b);
     btnNuevo.setEnabled(!b);
     
     
 }
 public void limpiarVentana(){
     txtBarrio.setText("Alte Brown");
     txtCura.setText("");
     txtDNINiño.setText("");
     txtDomPadres.setText("");
     txtDomiParroq.setText("");
     txtFechNacimNiño.setText("");
     txtFolio.setText("");
     txtLugarNacNiño.setText("");
     txtMadre.setText("");
     txtNombMadrina.setText("");
     txtNombNiño.setText("");
     txtNombPadre.setText("");
     txtNombPadrino.setText("");
     txtNombParroquia.setText("Parroquia San Pedro y San Pablo");
     txtPartida.setText("");
     txtareaMarginal.setText("");
     txtlibro.setText("");
     cmbCiudad.setSelectedItem("San Salvador de Jujuy");
     cmbProvincia.setSelectedItem("Jujuy");
     dtchFechaBautismo.cleanup();
 }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAgragCura;
    private javax.swing.JButton btnAgregarMadreCertficado;
    private javax.swing.JButton btnAgregarMadrinaCertficado;
    private javax.swing.JButton btnAgregarNiñoCertficado;
    private javax.swing.JButton btnAgregarPadreCertficado;
    private javax.swing.JButton btnAgregarPadrinoCertficado;
    private javax.swing.JButton btnBuscarCertificado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private com.toedter.calendar.JDateChooser dtchFechaBautismo;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCura;
    private javax.swing.JTextField txtDNINiño;
    private javax.swing.JTextField txtDomPadres;
    private javax.swing.JTextField txtDomiParroq;
    private javax.swing.JTextField txtFechNacimNiño;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtLugarNacNiño;
    private javax.swing.JTextField txtMadre;
    private javax.swing.JTextField txtNombMadrina;
    public javax.swing.JTextField txtNombNiño;
    private javax.swing.JTextField txtNombPadre;
    private javax.swing.JTextField txtNombPadrino;
    private javax.swing.JTextField txtNombParroquia;
    private javax.swing.JTextField txtPartida;
    private javax.swing.JTextArea txtareaMarginal;
    private javax.swing.JTextField txtlibro;
    // End of variables declaration//GEN-END:variables
}
