/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.CertificadoDAO;
import dao.PersonaDAO;
import dao.imp.CertificadoDAOImp;
import dao.imp.ParroquiaDaoImp;
import dao.imp.PersonaDAOImp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.*;
import dominio.Certificado;
import dominio.Parroquia;
import dominio.Persona;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import reporte.ReporteCertificadoJRDataSource;
import util.FechaUtil;
import util.mensajero;

/**
 *
 * @author AnahiAramayo
 */
public class AltaCertificado extends javax.swing.JFrame {

    private Persona pAhijado;
    private Persona pTutor;
    private Persona pTutora;
    private Persona pPadrino;
    private Persona pMadrina;
    private String qPersona;
    private Integer idPersona;
    PersonaDAO personaDAO = new PersonaDAOImp();
    private Certificado certificado = null;
    private boolean modificar;
    Parroquia p = null;

    /**
     * PE Creates new form Inicio
     */
    public AltaCertificado() {
        initComponents();

        // La primera vez que use el sistema debe cargar los datos de confiugarcion obligatoriamente
        try {
            List<Parroquia> lista = new ParroquiaDaoImp().listarParroquia();
            if (lista.isEmpty()) {
                Configuaracion configur = new Configuaracion(this, true);
                // si cargo todo bien entonces debe mostrarse el formulario del certificado
                if (!configur.isOperacionOk()) {
                    System.exit(0);
                }
            } else {
                // ya se configuro los datos , entonces inicio con el formulario de certifacdo
                p = lista.get(0);
            }

            limpiarVentana();
            
        } catch (org.hibernate.exception.JDBCConnectionException e) {
            // no se pudo abrir la bd
            mensajero.mensajeError(this, "No se puede Conectar a la BD, por favor active servidor y vuelva a ejecutar la aplicacion");
            System.exit(0);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnBuscarCertificado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombNiño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombPadre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombMadre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDNINiño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDomPadres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombPadrino = new javax.swing.JTextField();
        txtNombMadrina = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtlibro = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        txtPartida = new javax.swing.JTextField();
        btnAgregarNiñoCertficado = new javax.swing.JButton();
        btnAgregarPadreCertficado = new javax.swing.JButton();
        btnAgregarMadreCertficado = new javax.swing.JButton();
        txtFechNacimNiño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarPadrinoCertficado = new javax.swing.JButton();
        btnAgregarMadrinaCertficado = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtLugarNacNiño = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtCura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateFechaBautismo = new com.toedter.calendar.JDateChooser();
        txtCiudadParroquia = new javax.swing.JTextField();
        txtNombreParroquia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuItmNuevo = new javax.swing.JMenuItem();
        mnuItmEditar = new javax.swing.JMenuItem();
        mnuItmGuardar = new javax.swing.JMenuItem();
        mnuItmImprimir = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuItmSalir = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnuItemDatoParroquia = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Certificado");
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(850, 720));
        setMinimumSize(new java.awt.Dimension(850, 720));
        setPreferredSize(new java.awt.Dimension(850, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoNuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setEnabled(false);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setOpaque(false);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoLimpiar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setOpaque(false);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnEditar);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoGuardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(false);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoImprimir.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setEnabled(false);
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar2.add(btnImprimir);

        btnBuscarCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoBuscar.png"))); // NOI18N
        btnBuscarCertificado.setText("BUSCAR");
        btnBuscarCertificado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCertificado.setOpaque(false);
        btnBuscarCertificado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCertificadoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnBuscarCertificado);

        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(170, 10, 460, 110);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos - Certificado de Bautismo", 0, 0, new java.awt.Font("Calibri", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 600));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Bautizado:");

        txtNombNiño.setEditable(false);
        txtNombNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombNiñoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Padre:");

        txtNombPadre.setEditable(false);
        txtNombPadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Madre:");

        txtNombMadre.setEditable(false);
        txtNombMadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Provincia:");

        cmbProvincia.setEditable(true);
        cmbProvincia.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jujuy", "Salta", "Tucuman", "Mendoza", "La Rioja ", "Bs As", "Santa Fe", "Cordoba", "Corrientes", "Misiones", "Entre Rios", "Tierra del Fuego", " ", " " }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("D.N.I.:");

        txtDNINiño.setEditable(false);
        txtDNINiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Domicilio Padres:");

        txtDomPadres.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDomPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomPadresActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Nombre Padrino:");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Nombre Madrina:");

        txtNombPadrino.setEditable(false);
        txtNombPadrino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombPadrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombPadrinoActionPerformed(evt);
            }
        });

        txtNombMadrina.setEditable(false);
        txtNombMadrina.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombMadrina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombMadrinaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Libro:");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Folio:");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Partida:");

        txtlibro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtlibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlibroKeyTyped(evt);
            }
        });

        txtFolio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        txtPartida.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtPartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPartidaKeyTyped(evt);
            }
        });

        btnAgregarNiñoCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarNiñoCertficado.setText("Agregar Bautizado");
        btnAgregarNiñoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNiñoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarPadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarPadreCertficado.setText("Agregar Padre");
        btnAgregarPadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadreCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarMadreCertficado.setText("Agregar Madre");
        btnAgregarMadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadreCertficadoActionPerformed(evt);
            }
        });

        txtFechNacimNiño.setEditable(false);
        txtFechNacimNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFechNacimNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechNacimNiñoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Parroquia:");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Parroco");

        btnAgregarPadrinoCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarPadrinoCertficado.setText("Agregar Padrino");
        btnAgregarPadrinoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadrinoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadrinaCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarMadrinaCertficado.setText("Agregar Madrina");
        btnAgregarMadrinaCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadrinaCertficadoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Lugar de Nacimiento:");

        txtLugarNacNiño.setEditable(false);
        txtLugarNacNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtLugarNacNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarNacNiñoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Ciudad:");

        cmbCiudad.setEditable(true);
        cmbCiudad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San Salvador de Jujuy", "Abra Pampa", "Abralaite", "Aguas Calientes", "Alfarcito", "Arrayanal", "Arroyo Colorado", "Bárcena", "Barrancas", "Barrios", "Bermejito", "Caimancito", "Calilegua", "Cangrejillos", "Carahunco", "Casabindo", "Casira", "Caspalá", "Catúa", "Centro Forestal", "Chalicán", "Cieneguillas", "Cochinoca", "Coctaca", "Colonia San José", "El Cóndor", "Coranzulí", "Cusi Cusi", "Don Emilio", "El Acheral", "El Aguilar", "El Angosto", "El Bananal", "El Carmen", "El Ceibal", "El Fuerte", "El Moreno", "El Piquete", "El Puesto", "El Quemado", "El Talar", "El Toro", "Fraile Pintado", "Guerrero", "Hipólito Yrigoyen", "Iturbe", "Hornaditas", "Huacalera", "Huancar", "Humahuaca", "Juella", "La Almona", "La Ciénaga", "La Esperanza", "La Intermedia", "La Manga", "La Mendieta", "La Quiaca", "Lagunillas", "León", "Libertador General San Martín", "Libertad", "Liviara", "Llulluchayoc", "Los Lapachos", "Los Manatiales", "Loteo Navea", "Lozano", "Maimará", "Mina 9 de Octubre", "Mina Pirquitas", "Miraflores", "Misa Rumi", "Monterrico", "Ocloyas", "Olaroz Chico", "Oratorio", "Paicone", "Palma Sola", "Palo Blanco", "Palpalá", "Pampa Planca", "Pampichuela", "Parapeti", "Paulina", "Perico", "Piedritas", "Puente Lavayén", "Puesto del Marqués", "Puesto Sey", "Puesto Viejo", "Pumahuasi", "Purmamarca", "Rinconada", "Rinconadilla", "Rodeíto", "Rosario del Río Grande", "San Antonio", "San Pedro", "San Francisco", "San Juan de Oros", "San Lucas", "San Pedro de Jujuy", "Santa Ana", "Santa Catalina", "Santa Clara", "Sauzal", "Susques", "Tabladitas", "Tafna", "Termas de Reyes", "Tilcara", "Tiraxi", "Tres Cruces", "Tres Pozos", "Tumbaya", "Tusaquillas", "Uquía", "Valle Colorado", "Valle Grande", "Vinalito", "Volcán", "Yala", "Yavi", "Yavi Chico", "Yoscaba", "Yuto" }));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setText("Ciudad");

        txtCura.setEditable(false);
        txtCura.setText("constante");
        txtCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Fecha del dia de bautismo:");

        dateFechaBautismo.setDate(new Date());

        txtCiudadParroquia.setEditable(false);
        txtCiudadParroquia.setText("constante");
        txtCiudadParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadParroquiaActionPerformed(evt);
            }
        });

        txtNombreParroquia.setEditable(false);
        txtNombreParroquia.setText("constante");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Datos del Ahijado/a");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Datos de los Padres");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos de los Padrinos");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCura, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                            .addComponent(txtNombreParroquia))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCiudadParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtLugarNacNiño)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDNINiño))
                                            .addComponent(txtNombNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregarNiñoCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregarPadreCertficado)
                                            .addComponent(btnAgregarMadreCertficado))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombPadrino, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnAgregarPadrinoCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNombMadrina, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAgregarMadrinaCertficado)))
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                                        .addComponent(jLabel23))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator4))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNombreParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel19)
                        .addComponent(txtCiudadParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel20)
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarNiñoCertficado))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNINiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugarNacNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel21))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombPadrino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(txtNombMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarPadrinoCertficado)
                            .addComponent(btnAgregarMadreCertficado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNombMadrina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarMadrinaCertficado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 820, 540);
        jPanel1.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 670);

        menuBar.setBackground(new java.awt.Color(153, 204, 255));

        fileMenu.setBackground(new java.awt.Color(153, 204, 255));
        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        mnuItmNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuItmNuevo.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmNuevo.setMnemonic('o');
        mnuItmNuevo.setText("Nuevo Certificado");
        mnuItmNuevo.setEnabled(false);
        mnuItmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmNuevoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmNuevo);

        mnuItmEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuItmEditar.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmEditar.setText("Editar");
        mnuItmEditar.setEnabled(false);
        mnuItmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmEditarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmEditar);

        mnuItmGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mnuItmGuardar.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmGuardar.setMnemonic('s');
        mnuItmGuardar.setText("Guardar");
        mnuItmGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmGuardarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmGuardar);

        mnuItmImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mnuItmImprimir.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmImprimir.setMnemonic('a');
        mnuItmImprimir.setText("Imprimir");
        mnuItmImprimir.setEnabled(false);
        mnuItmImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmImprimirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmImprimir);
        fileMenu.add(jSeparator5);

        mnuItmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuItmSalir.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmSalir.setMnemonic('x');
        mnuItmSalir.setText("Salir");
        mnuItmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmSalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmSalir);

        menuBar.add(fileMenu);

        mnuConfiguracion.setBackground(new java.awt.Color(153, 204, 255));
        mnuConfiguracion.setText("Configuracion");

        mnuItemDatoParroquia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuItemDatoParroquia.setBackground(new java.awt.Color(153, 204, 255));
        mnuItemDatoParroquia.setText("Datos Parroquia");
        mnuItemDatoParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDatoParroquiaActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuItemDatoParroquia);

        menuBar.add(mnuConfiguracion);

        helpMenu.setBackground(new java.awt.Color(153, 204, 255));
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        contentMenuItem.setBackground(new java.awt.Color(153, 204, 255));
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmSalirActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        new AcercaApp(this, true);

    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (modificar == false) {
            certificado = new Certificado();
        }
        CertificadoDAO certificadoDAO = new CertificadoDAOImp();


        try {

            certificado.setIdAhijado(pAhijado.getDni());
            certificado.setIdTutor(pTutor.getDni());
            certificado.setIdTutora(pTutora.getDni());
            certificado.setIdMadrina(pMadrina.getDni());
            certificado.setIdPadrino(pPadrino.getDni());
            certificado.setNombreCura(p.getApellidoCura() + " " + p.getNombreCura());

            certificado.setDomicilioPadres(txtDomPadres.getText().toUpperCase());
            certificado.setCiudad(cmbCiudad.getSelectedItem().toString());
            certificado.setProvincia(cmbProvincia.getSelectedItem().toString());
            certificado.setFechaBautizmo(dateFechaBautismo.getDate());
            certificado.setLibro(txtlibro.getText().toUpperCase());
            certificado.setPartida(txtPartida.getText().toUpperCase());
            certificado.setFolio(txtFolio.getText().toUpperCase());
            certificado.setNotasMarginales("no es necesario este campo");
            // se creo un certificado nuevo
            if (modificar == false) {
                certificadoDAO.insert(certificado);
            } else {
                // se cargo un certificado para actualizarlo
                certificadoDAO.update(certificado);
            }
            JOptionPane.showMessageDialog(null, "Se cargo correctamente...");
//            if (!modificar){
                  setEnabledComponentes(false);       
//            }
         
            //cuando guarda o actualiza esto se debe 
            btnEditar.setEnabled(true);
            mnuItmEditar.setEnabled(true);
            btnBuscarCertificado.setEnabled(false);
            
            activarBotonNuevo(false);
            
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    public void Imprimir(){
        Map parametros = new HashMap();
        String logotipo = "/images/1.jpg";

        ReporteCertificadoJRDataSource dataSource = new ReporteCertificadoJRDataSource();
        List<Certificado> lista = new ArrayList<Certificado>();
        lista.add(certificado);
        dataSource.setListCertificado(lista);
        JasperPrint jPrintt;
        
        try {
            jPrintt = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reporte/CertificadoParroquia.jasper"), (Map) parametros, dataSource);
          
            // este metodo imprime el reporte , recibe el jprint(el informe, ) y el otro parametro es para decirle que muestre la pantalla de configuracion de la impresora
            // si es false imprime de una con la configuarcion por defecto.
            JasperPrintManager.printReport(jPrintt, true);
            // esto es para la vista previa
//            JDialog reporte = new JDialog();
//            reporte.setSize(900, 700);
//            reporte.setLocationRelativeTo(null);
//            reporte.setModal(true);
//            reporte.setTitle("INFORME");
//            JRViewer jv = new JRViewer(jPrintt);
//            reporte.getContentPane().add(jv);
//            reporte.setVisible(true);

        } catch (JRException ex) {
            mensajero.mensajeError(this, "Error de Impresion");
        }

    }
    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
         Imprimir();
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

             setEnabledComponentes(true);
             btnEditar.setEnabled(false);
             mnuItmEditar.setEnabled(false);
             btnImprimir.setEnabled(false);
             mnuItmImprimir.setEnabled(false);
             btnGuardar.setEnabled(true);
             mnuItmGuardar.setEnabled(true);
             btnNuevo.setEnabled(true);
             mnuItmNuevo.setEnabled(true);
             
        
        
        
        
        //        limpiarVentana();
//
//        // el indicador de modificar se pne en false ya que se creara un certificado nuevo
//        modificar = false;
//        // inicializar los botones de opciones
//        btnNuevo.setEnabled(true);
//        btnGuardar.setEnabled(false);
//        btnImprimir.setEnabled(false);
//        btnBuscarCertificado.setEnabled(true);
//
//        //mnuitm
//        mnuItmNuevo.setEnabled(true);
//        mnuItmGuardar.setEnabled(false);
//        mnuItmImprimir.setEnabled(false);



    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCertificadoActionPerformed

        // abre la ventana de busqueda 
        BusquedaCertificado bc = new BusquedaCertificado(certificado, this, true, txtNombPadrino, "padrino");

        // listar 
        if (bc.getCertificado() != null) {
            // indicador de qeu se esta por cargar un certificado existente 
            modificar = true;
           
           
            // para que no se pueda modifar  si lo quiere hacer teine que teclear el boton editar
            setEnabledComponentes(false);
            // para que se pueda imprimir 
            btnImprimir.setEnabled(true);
            btnGuardar.setText("Actualizar");
//            btnGuardar.setEnabled(true);
            btnGuardar.setEnabled(false);
            btnEditar.setEnabled(true);
            mnuItmEditar.setEnabled(true);
            //mnuItem
            mnuItmImprimir.setEnabled(true);
//            mnuItmGuardar.setEnabled(true);
            mnuItmGuardar.setEnabled(false);
            mnuItmGuardar.setText("Actualizar");
            btnEditar.setEnabled(true);
            //llenar todos los campos de con los datosd del certificacdo}
            //obtengo el certificado por parametro desde la ventana busqueda certificado
            certificado = bc.getCertificado();

            //obtengo los datos del tutor,tutora,madrina,padrino,ahijado a traves del certificado obtenido
            pTutor = new PersonaDAOImp().getPersona(certificado.getIdTutor());
            pTutora = new PersonaDAOImp().getPersona(certificado.getIdTutora());
            pPadrino = new PersonaDAOImp().getPersona(certificado.getIdPadrino());
            pMadrina = new PersonaDAOImp().getPersona(certificado.getIdMadrina());
            pAhijado = new PersonaDAOImp().getPersona(certificado.getIdAhijado());
//            System.out.println("ahijado buscado  " + pAhijado.getIdPersona());
//            System.out.println("madrina buscado  " + pMadrina.getIdPersona());
//            System.out.println("padrino buscado  " + pPadrino.getIdPersona());
//            System.out.println("tutor buscado  " + pTutor.getIdPersona());
//            System.out.println("tutora buscado  " + pTutora.getIdPersona());
//            System.out.println("id certificado  " + certificado.getNumeroCertificado());

            //datos de la configuarcion de la parroquia
            txtCiudadParroquia.setText(p.getCiudadParroquia());
            txtNombreParroquia.setText(p.getNombreParroquia());

            //otros datos de certificado
            txtFolio.setText(certificado.getFolio());
            txtPartida.setText(certificado.getPartida());
            txtlibro.setText(certificado.getLibro());
            cmbCiudad.setSelectedItem(certificado.getCiudad());
            cmbProvincia.setSelectedItem(certificado.getProvincia());
            dateFechaBautismo.setDate(certificado.getFechaBautizmo());

            //cura que lo bautizo
            txtCura.setText(certificado.getNombreCura());

            //datos del bautizado
            txtNombNiño.setText(pAhijado.getApellido() + " " + pAhijado.getNombre());
            txtDNINiño.setText(String.valueOf(pAhijado.getDni()));
            txtFechNacimNiño.setText(FechaUtil.getDateDD_MM_AAAA(pAhijado.getFechaNaciemiento()));
            txtLugarNacNiño.setText(pAhijado.getLugarNacimiento());

            //tutor o padre --tutora o madre -- madrina -- padrino
            txtNombPadre.setText(pTutor.getApellido() + " " + pTutor.getNombre());
            txtNombMadre.setText(pTutora.getApellido() + " " + pTutora.getNombre());
            txtNombMadrina.setText(pMadrina.getApellido() + " " + pMadrina.getNombre());
            txtNombPadrino.setText(pPadrino.getApellido() + " " + pPadrino.getNombre());
            //domicilio de los padres
            txtDomPadres.setText(certificado.getDomicilioPadres());






        }
    }//GEN-LAST:event_btnBuscarCertificadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        pAhijado = null;
        pTutor=null;
        pTutora=null;
        pPadrino=null;
        pMadrina = null;
        
        
        
        
        setEnabledComponentes(true);
        btnEditar.setEnabled(false);
        mnuItmEditar.setEnabled(false);
        
        limpiarVentana();
        btnNuevo.setEnabled(false);
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(true);

        btnImprimir.setEnabled(false);
        btnBuscarCertificado.setEnabled(true);

        //mnuItm
        mnuItmNuevo.setEnabled(false);
        mnuItmGuardar.setText("Guardar");
        mnuItmGuardar.setEnabled(true);
        mnuItmImprimir.setEnabled(false);

        certificado = new Certificado();
        modificar = false;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void mnuItemDatoParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDatoParroquiaActionPerformed
        Configuaracion config = new Configuaracion(this, true);
        limpiarVentana();
    }//GEN-LAST:event_mnuItemDatoParroquiaActionPerformed

    private void mnuItmGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmGuardarActionPerformed
        btnGuardarActionPerformed(evt);

    }//GEN-LAST:event_mnuItmGuardarActionPerformed

    private void mnuItmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmNuevoActionPerformed

        btnNuevoActionPerformed(evt);

//       //mnuItm 
//       mnuItmNuevo.setEnabled(false);
//       mnuItmGuardar.setEnabled(true);
//       mnuItmImprimir.setEnabled(true);
//       mnuItmGuardar.setText("Guardar");
//       
//       

        modificar = false;


    }//GEN-LAST:event_mnuItmNuevoActionPerformed

    private void mnuItmImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmImprimirActionPerformed
        btnImprimirActionPerformed(evt);
    }//GEN-LAST:event_mnuItmImprimirActionPerformed

    private void mnuItmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmEditarActionPerformed
          btnEditarActionPerformed(evt);

    }//GEN-LAST:event_mnuItmEditarActionPerformed

    private void txtCiudadParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadParroquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadParroquiaActionPerformed

    private void txtCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuraActionPerformed

    private void txtLugarNacNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarNacNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarNacNiñoActionPerformed

    private void btnAgregarMadrinaCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadrinaCertficadoActionPerformed
        BusquedaPersona bp = new BusquedaPersona(this, true);

        if (bp.isAgregado()) {
            pMadrina = bp.getPersona();

            txtNombMadrina.setText(pMadrina.getApellido() + " " + pMadrina.getNombre());

        }
    }//GEN-LAST:event_btnAgregarMadrinaCertficadoActionPerformed

    private void btnAgregarPadrinoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadrinoCertficadoActionPerformed

        BusquedaPersona bp = new BusquedaPersona(this, true);

        if (bp.isAgregado()) {

            pPadrino = bp.getPersona();

            txtNombPadrino.setText(pPadrino.getApellido() + " " + pPadrino.getNombre());
        }

    }//GEN-LAST:event_btnAgregarPadrinoCertficadoActionPerformed

    private void txtFechNacimNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechNacimNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechNacimNiñoActionPerformed

    private void btnAgregarMadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadreCertficadoActionPerformed
        BusquedaPersona bp = new BusquedaPersona(this, true);

        if (bp.isAgregado()) {
            pTutora = bp.getPersona();

            txtNombMadre.setText(pTutora.getApellido() + " " + pTutora.getNombre());

        }
    }//GEN-LAST:event_btnAgregarMadreCertficadoActionPerformed

    private void btnAgregarPadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadreCertficadoActionPerformed

        BusquedaPersona bp = new BusquedaPersona(this, true);

        if (bp.isAgregado()) {
            pTutor = bp.getPersona();
            txtNombPadre.setText(pTutor.getApellido() + " " + pTutor.getNombre());
        }
    }//GEN-LAST:event_btnAgregarPadreCertficadoActionPerformed

    private void btnAgregarNiñoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNiñoCertficadoActionPerformed

        //llamo a la ventana busqueda

        BusquedaPersona bp = new BusquedaPersona(this, true);

        // agrego la persona buscada al certificado

        if (bp.isAgregado()) {
            pAhijado = bp.getPersona();

            txtFechNacimNiño.setText(FechaUtil.getFechaString10DDMMAAAA(pAhijado.getFechaNaciemiento()));
            txtDNINiño.setText(String.valueOf(pAhijado.getDni()));
            txtLugarNacNiño.setText(pAhijado.getLugarNacimiento());
            txtNombNiño.setText(pAhijado.getApellido() + " " + pAhijado.getNombre());
        }
    }//GEN-LAST:event_btnAgregarNiñoCertficadoActionPerformed

    private void txtPartidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartidaKeyTyped
        consumirLetras(evt);
    }//GEN-LAST:event_txtPartidaKeyTyped

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        consumirLetras(evt);
    }//GEN-LAST:event_txtFolioKeyTyped

    private void txtlibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlibroKeyTyped
        consumirLetras(evt);
    }//GEN-LAST:event_txtlibroKeyTyped

    private void txtNombMadrinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombMadrinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombMadrinaActionPerformed

    private void txtNombPadrinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombPadrinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombPadrinoActionPerformed

    private void txtDomPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomPadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomPadresActionPerformed

    private void txtNombNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombNiñoActionPerformed
    public void consumirLetras(java.awt.event.KeyEvent evt) {
        // conusmir los caracteres del legajo excepto los numeros
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }

    public void activarBotonNuevo(boolean b) {
        btnGuardar.setEnabled(b);
        btnImprimir.setEnabled(!b);
        btnNuevo.setEnabled(!b);

        // mnuItm tambien hacer lo mismo
        mnuItmGuardar.setEnabled(b);
        mnuItmImprimir.setEnabled(!b);
        mnuItmNuevo.setEnabled(!b);

    }

    public void limpiarVentana() {
        // Datos de Configuarcion . datos constantes
        p = new ParroquiaDaoImp().listarParroquia().get(0);
        txtCiudadParroquia.setText(p.getCiudadParroquia());
        txtCura.setText(p.getApellidoCura() + " " + p.getNombreCura());
        txtNombreParroquia.setText(p.getNombreParroquia());

        // datos del form
        txtDNINiño.setText("");
        txtDomPadres.setText("");
        txtFechNacimNiño.setText("");
        txtFolio.setText("");
        txtLugarNacNiño.setText("");
        txtNombMadre.setText("");
        txtNombMadrina.setText("");
        txtNombNiño.setText("");
        txtNombPadre.setText("");
        txtNombPadrino.setText("");
        txtPartida.setText("");
//     txtareaMarginal.setText("");
        txtlibro.setText("");
        cmbCiudad.setSelectedItem(p.getCiudadParroquia());
        cmbProvincia.setSelectedItem("Jujuy");
        dateFechaBautismo.setDate(new Date());
    }
     /**
      * Este metodo desactiva o activa  los componetnes (botones , cajas de texto , cmb, ..) para q el usuario no pueda modificar
      * esto es dependiendo el parametro que se le pase true o false.
      */
     public void setEnabledComponentes(boolean b){
         dateFechaBautismo.setEnabled(b);
         txtlibro.setEnabled(b);
         txtPartida.setEnabled(b);
         txtFolio.setEnabled(b);
         txtDomPadres.setEnabled(b);
         cmbCiudad.setEnabled(b);
         cmbProvincia.setEnabled(b);
         btnAgregarMadreCertficado.setEnabled(b);
         btnAgregarMadrinaCertficado.setEnabled(b);
         btnAgregarNiñoCertficado.setEnabled(b);
         btnAgregarPadreCertficado.setEnabled(b);
         btnAgregarPadrinoCertficado.setEnabled(b);
        
         
     }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMadreCertficado;
    private javax.swing.JButton btnAgregarMadrinaCertficado;
    private javax.swing.JButton btnAgregarNiñoCertficado;
    private javax.swing.JButton btnAgregarPadreCertficado;
    private javax.swing.JButton btnAgregarPadrinoCertficado;
    private javax.swing.JButton btnBuscarCertificado;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JMenuItem contentMenuItem;
    private com.toedter.calendar.JDateChooser dateFechaBautismo;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenuItem mnuItemDatoParroquia;
    private javax.swing.JMenuItem mnuItmEditar;
    private javax.swing.JMenuItem mnuItmGuardar;
    private javax.swing.JMenuItem mnuItmImprimir;
    private javax.swing.JMenuItem mnuItmNuevo;
    private javax.swing.JMenuItem mnuItmSalir;
    private javax.swing.JTextField txtCiudadParroquia;
    private javax.swing.JTextField txtCura;
    private javax.swing.JTextField txtDNINiño;
    private javax.swing.JTextField txtDomPadres;
    private javax.swing.JTextField txtFechNacimNiño;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtLugarNacNiño;
    private javax.swing.JTextField txtNombMadre;
    private javax.swing.JTextField txtNombMadrina;
    public javax.swing.JTextField txtNombNiño;
    private javax.swing.JTextField txtNombPadre;
    private javax.swing.JTextField txtNombPadrino;
    private javax.swing.JTextField txtNombreParroquia;
    private javax.swing.JTextField txtPartida;
    private javax.swing.JTextField txtlibro;
    // End of variables declaration//GEN-END:variables
}
