/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.CertificadoDAO;
import dao.PersonaDAO;
import dao.imp.CertificadoDAOImp;
import dao.imp.ParroquiaDaoImp;
import dao.imp.PersonaDAOImp;
import java.awt.Color;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import modelo.Certificado;
import modelo.Parroquia;
import modelo.Persona;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import reporte.ReporteCertificadoJRDataSource;
import util.FechaUtil;
import util.mensajero;



/**
 *
 * @author AnahiAramayo
 */
public class AltaCertificado extends javax.swing.JFrame {
    private Persona pCura;
    private Persona pAhijado;
    private Persona pTutor;
    private Persona pTutora;
    private Persona pPadrino;
    private Persona pMadrina;
    private String qPersona;
    private Integer idPersona;
    Persona cura;
    Persona tutor;
    Persona tutora;
    Persona padrino;
    Persona madrina;
    Persona ahijado;
    PersonaDAO personaDAO =new PersonaDAOImp();
    ArrayList<Persona> listDeCuras = new ArrayList<Persona>();
    private Certificado certificado= null;
    
    private boolean modificar;
    Parroquia p = null;
    /**PE
     * Creates new form Inicio
     */
    public AltaCertificado() {
        initComponents();
       
        // La primera vez que use el sistema debe cargar los datos de confiugarcion obligatoriamente
        try {
         List<Parroquia>  lista = new ParroquiaDaoImp().listarParroquia();
           if (lista.isEmpty()) {
            Configuaracion configur =  new Configuaracion(this, true);
            // si cargo todo bien entonces debe mostrarse el formulario del certificado
                 if (!configur.isOperacionOk()) {
                    System.exit(0);
                 }
           }else{
            // ya se configuro los datos , entonces inicio con el formulario de certifacdo
            p = lista.get(0);
//            new ParroquiaDaoImp().deleteParroquia(p);
            }
        
             limpiarVentana();

        } catch (org.hibernate.exception.JDBCConnectionException e) {
            // no se pudo abrir la bd
            mensajero.mensajeError(this, "No se puede Conectar a la BD, por favor active servidor y vuelva a ejecutar la aplicacion");
            System.exit(0);
        }
        
       
    }
    
    
    
    public void agregar(Persona p,JTextField tipoPersona,String qPersona){
        this.qPersona = qPersona;
        //this.idPersona = idPerso;
        tipoPersona.setText(p.getApellido()+", "+p.getNombre());
        
        if ("cura".equals(qPersona)) {
            cura = p;
            this.pCura = p;
        } else {
            if ("tutor".equals(qPersona)) {
                tutor = p;
                this.pTutor = p;
            } else {
                if ("tutora".equals(qPersona)) {
                    tutora= p;
                    this.pTutora = p;
                } else {
                    if ("padrino".equals(qPersona)) {
                        padrino=p;
                        this.pPadrino = p;
                    } else {
                        if ("madrina".equals(qPersona)) {
                            madrina=p;
                            this.pMadrina = p;
                        } else {
                            ahijado=p;
                            this.pAhijado = p;
                        }
                    }
                }
            }
        }
        p = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarCertificado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombNiño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombPadre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMadre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDNINiño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDomPadres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombPadrino = new javax.swing.JTextField();
        txtNombMadrina = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtlibro = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        txtPartida = new javax.swing.JTextField();
        btnAgregarNiñoCertficado = new javax.swing.JButton();
        btnAgregarPadreCertficado = new javax.swing.JButton();
        btnAgregarMadreCertficado = new javax.swing.JButton();
        txtFechNacimNiño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarPadrinoCertficado = new javax.swing.JButton();
        btnAgregarMadrinaCertficado = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtLugarNacNiño = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtCura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dtchFechaBautismo = new com.toedter.calendar.JDateChooser();
        txtCiudadParroquia = new javax.swing.JTextField();
        txtNombreParroquia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuItmNuevo = new javax.swing.JMenuItem();
        mnuItmGuardar = new javax.swing.JMenuItem();
        mnuItmImprimir = new javax.swing.JMenuItem();
        mnuItmLimpiar = new javax.swing.JMenuItem();
        mnuItmSalir = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnuItemDatoParroquia = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Certificado");
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 720));
        setMinimumSize(new java.awt.Dimension(1100, 720));
        setPreferredSize(new java.awt.Dimension(1100, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoNuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setOpaque(false);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(false);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGuardar);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoImprimir.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar2.add(btnImprimir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoLimpiar.png"))); // NOI18N
        btnCancelar.setText("Limpiar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(false);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCancelar);

        btnBuscarCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoBuscar.png"))); // NOI18N
        btnBuscarCertificado.setText("Buscar ");
        btnBuscarCertificado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarCertificado.setOpaque(false);
        btnBuscarCertificado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCertificadoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnBuscarCertificado);

        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(290, 10, 460, 110);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos - Certificado de Bautismo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 600));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Bautizado:");

        txtNombNiño.setEditable(false);
        txtNombNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombNiñoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Padre:");

        txtNombPadre.setEditable(false);
        txtNombPadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Madre:");

        txtMadre.setEditable(false);
        txtMadre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Provincia:");

        cmbProvincia.setEditable(true);
        cmbProvincia.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jujuy", "Salta", "Tucuman", "Mendoza", "La Rioja ", "Bs As", "Santa Fe", "Cordoba", "Corrientes", "Misiones", "Entre Rios", "Tierra del Fuego", " ", " " }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("D.N.I.:");

        txtDNINiño.setEditable(false);
        txtDNINiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Domicilio Padres:");

        txtDomPadres.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDomPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomPadresActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Nombre Padrino:");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Nombre Madrina:");

        txtNombPadrino.setEditable(false);
        txtNombPadrino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombPadrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombPadrinoActionPerformed(evt);
            }
        });

        txtNombMadrina.setEditable(false);
        txtNombMadrina.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNombMadrina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombMadrinaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Libro:");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Folio:");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Partida:");

        txtlibro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtlibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlibroKeyTyped(evt);
            }
        });

        txtFolio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        txtPartida.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtPartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPartidaKeyTyped(evt);
            }
        });

        btnAgregarNiñoCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarNiñoCertficado.setText("Agregar Bautizado");
        btnAgregarNiñoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNiñoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarPadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarPadreCertficado.setText("Agregar Padre");
        btnAgregarPadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadreCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadreCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarMadreCertficado.setText("Agregar Madre");
        btnAgregarMadreCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadreCertficadoActionPerformed(evt);
            }
        });

        txtFechNacimNiño.setEditable(false);
        txtFechNacimNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFechNacimNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechNacimNiñoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Parroquia:");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Pbro./Diacono:");

        btnAgregarPadrinoCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarPadrinoCertficado.setText("Agregar Padrino");
        btnAgregarPadrinoCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadrinoCertficadoActionPerformed(evt);
            }
        });

        btnAgregarMadrinaCertficado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAgregarMadrinaCertficado.setText("Agregar Madrina");
        btnAgregarMadrinaCertficado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMadrinaCertficadoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Lugar de Nacimiento:");

        txtLugarNacNiño.setEditable(false);
        txtLugarNacNiño.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtLugarNacNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarNacNiñoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Ciudad:");

        cmbCiudad.setEditable(true);
        cmbCiudad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "San Salvador de Jujuy", "Abra Pampa", "Abralaite", "Aguas Calientes", "Alfarcito", "Arrayanal", "Arroyo Colorado", "Bárcena", "Barrancas", "Barrios", "Bermejito", "Caimancito", "Calilegua", "Cangrejillos", "Carahunco", "Casabindo", "Casira", "Caspalá", "Catúa", "Centro Forestal", "Chalicán", "Cieneguillas", "Cochinoca", "Coctaca", "Colonia San José", "El Cóndor", "Coranzulí", "Cusi Cusi", "Don Emilio", "El Acheral", "El Aguilar", "El Angosto", "El Bananal", "El Carmen", "El Ceibal", "El Fuerte", "El Moreno", "El Piquete", "El Puesto", "El Quemado", "El Talar", "El Toro", "Fraile Pintado", "Guerrero", "Hipólito Yrigoyen", "Iturbe", "Hornaditas", "Huacalera", "Huancar", "Humahuaca", "Juella", "La Almona", "La Ciénaga", "La Esperanza", "La Intermedia", "La Manga", "La Mendieta", "La Quiaca", "Lagunillas", "León", "Libertador General San Martín", "Libertad", "Liviara", "Llulluchayoc", "Los Lapachos", "Los Manatiales", "Loteo Navea", "Lozano", "Maimará", "Mina 9 de Octubre", "Mina Pirquitas", "Miraflores", "Misa Rumi", "Monterrico", "Ocloyas", "Olaroz Chico", "Oratorio", "Paicone", "Palma Sola", "Palo Blanco", "Palpalá", "Pampa Planca", "Pampichuela", "Parapeti", "Paulina", "Perico", "Piedritas", "Puente Lavayén", "Puesto del Marqués", "Puesto Sey", "Puesto Viejo", "Pumahuasi", "Purmamarca", "Rinconada", "Rinconadilla", "Rodeíto", "Rosario del Río Grande", "San Antonio", "San Pedro", "San Francisco", "San Juan de Oros", "San Lucas", "San Pedro de Jujuy", "Santa Ana", "Santa Catalina", "Santa Clara", "Sauzal", "Susques", "Tabladitas", "Tafna", "Termas de Reyes", "Tilcara", "Tiraxi", "Tres Cruces", "Tres Pozos", "Tumbaya", "Tusaquillas", "Uquía", "Valle Colorado", "Valle Grande", "Vinalito", "Volcán", "Yala", "Yavi", "Yavi Chico", "Yoscaba", "Yuto" }));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setText("Ciudad");

        txtCura.setEditable(false);
        txtCura.setText("constante");
        txtCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Fecha del dia de bautismo:");

        dtchFechaBautismo.setDate(new Date());

        txtCiudadParroquia.setEditable(false);
        txtCiudadParroquia.setText("constante");
        txtCiudadParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadParroquiaActionPerformed(evt);
            }
        });

        txtNombreParroquia.setEditable(false);
        txtNombreParroquia.setText("constante");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Datos del Ahijado/a");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Datos de los Padres");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos de los Padrinos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56)
                                .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarPadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarMadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombMadrina, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombPadrino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarPadrinoCertficado)
                            .addComponent(btnAgregarMadrinaCertficado))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombNiño)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDNINiño, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtLugarNacNiño)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNombreParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCura, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtchFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCiudadParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnAgregarNiñoCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNombreParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dtchFechaBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel19)
                            .addComponent(txtCiudadParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtNombNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNiñoCertficado))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtFechNacimNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNINiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(txtLugarNacNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtNombPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPadreCertficado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombPadrino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPadrinoCertficado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMadreCertficado)
                    .addComponent(jLabel13)
                    .addComponent(txtNombMadrina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMadrinaCertficado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(txtDomPadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 1060, 540);
        jPanel1.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 670);

        menuBar.setBackground(new java.awt.Color(153, 204, 255));

        fileMenu.setBackground(new java.awt.Color(153, 204, 255));
        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        mnuItmNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuItmNuevo.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmNuevo.setMnemonic('o');
        mnuItmNuevo.setText("Nuevo Certificado");
        mnuItmNuevo.setEnabled(false);
        mnuItmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmNuevoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmNuevo);

        mnuItmGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mnuItmGuardar.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmGuardar.setMnemonic('s');
        mnuItmGuardar.setText("Guardar");
        mnuItmGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmGuardarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmGuardar);

        mnuItmImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmImprimir.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmImprimir.setMnemonic('a');
        mnuItmImprimir.setText("Imprimir");
        mnuItmImprimir.setEnabled(false);
        mnuItmImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmImprimirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmImprimir);

        mnuItmLimpiar.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmLimpiar.setText("Limpiar ");
        mnuItmLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmLimpiarActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmLimpiar);

        mnuItmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmSalir.setBackground(new java.awt.Color(153, 204, 255));
        mnuItmSalir.setMnemonic('x');
        mnuItmSalir.setText("Salir");
        mnuItmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmSalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmSalir);

        menuBar.add(fileMenu);

        mnuConfiguracion.setBackground(new java.awt.Color(153, 204, 255));
        mnuConfiguracion.setText("Configuracion");

        mnuItemDatoParroquia.setBackground(new java.awt.Color(153, 204, 255));
        mnuItemDatoParroquia.setText("Datos Parroquia");
        mnuItemDatoParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemDatoParroquiaActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuItemDatoParroquia);

        menuBar.add(mnuConfiguracion);

        helpMenu.setBackground(new java.awt.Color(153, 204, 255));
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setBackground(new java.awt.Color(153, 204, 255));
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setBackground(new java.awt.Color(153, 204, 255));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Ayuda");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmSalirActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
         new AcercaApp(this, true);
        
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void btnAgregarNiñoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNiñoCertficadoActionPerformed
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        BusquedaPersona bp = new BusquedaPersona(pAhijado,this,true,txtNombNiño,"ahijado");
        bp.setVisible(true);
        //txtFechNacimNiño.setText(sdf.format(p.getFechaNaciemiento()));
        bp.setLocationRelativeTo(this);
        
        try {
            txtFechNacimNiño.setText(sdf.format(pAhijado.getFechaNaciemiento()));
            txtDNINiño.setText(pAhijado.getDni());
            //String fecha = sdf.format(p.getFechaNaciemiento());
            txtLugarNacNiño.setText(pAhijado.getLugarNacimiento());
            txtDNINiño.setText(pAhijado.getDni());            
        } catch (NullPointerException e) {
        }
        
        
//        txtNombNiño.setText(p.getApellido()+", " +p.getNombre());
//        txtNombPadre.setText(String.valueOf(p.getIdPersona()));
    }//GEN-LAST:event_btnAgregarNiñoCertficadoActionPerformed

    private void btnAgregarPadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadreCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pTutor,this,true,txtNombPadre,"tutor");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarPadreCertficadoActionPerformed

    public boolean validacion(){
        boolean vacio = true;
        ArrayList<JTextField> listaTxt = new ArrayList();
//        listaTxt.add(txtNombParroquia);
        listaTxt.add(txtCura);listaTxt.add(txtNombNiño);
        listaTxt.add(txtFechNacimNiño);listaTxt.add(txtDNINiño);
        listaTxt.add(txtLugarNacNiño);listaTxt.add(txtNombPadre);listaTxt.add(txtMadre);
        listaTxt.add(txtDomPadres);listaTxt.add(txtNombPadrino);listaTxt.add(txtNombMadrina);
        listaTxt.add(txtlibro);listaTxt.add(txtPartida);listaTxt.add(txtFolio);
        for (Iterator<JTextField> it = listaTxt.iterator(); it.hasNext();) {
            JTextField jTextField = it.next();
            if (jTextField.getText().equals("")) {
                jTextField.setBackground(Color.red);
                vacio = true;
                break;
            }else{
                vacio = false;
            }             
        }
        return vacio;
    }
    
    private void btnAgregarMadreCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadreCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pTutora,this,true,txtMadre,"tutora");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarMadreCertficadoActionPerformed

    private void btnAgregarPadrinoCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadrinoCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pPadrino,this,true,txtNombPadrino,"padrino");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarPadrinoCertficadoActionPerformed

    private void btnAgregarMadrinaCertficadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMadrinaCertficadoActionPerformed
        Persona p = new Persona();
        BusquedaPersona bp = new BusquedaPersona(pMadrina,this,true,txtNombMadrina,"madrina");
        bp.setVisible(true);
        bp.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAgregarMadrinaCertficadoActionPerformed

    private void txtDomPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomPadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomPadresActionPerformed

    private void txtNombNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombNiñoActionPerformed

    private void txtFechNacimNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechNacimNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechNacimNiñoActionPerformed

    private void txtNombMadrinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombMadrinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombMadrinaActionPerformed

    private void txtCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuraActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(modificar==false){
         certificado = new Certificado();
        }
        CertificadoDAO certificadoDAO = new CertificadoDAOImp();

//        certificado.setNombreParroquia(txtNombParroquia.getText());
//        certificado.setDomicilioParooquia(txtCiudadParroquia.getText());
       
        try {
            
//            certificado.setIdCura(cura.getIdPersona());
            certificado.setIdAhijado(ahijado.getIdPersona());
            certificado.setIdTutor(tutor.getIdPersona());
            certificado.setIdTutora(tutora.getIdPersona());
            certificado.setIdMadrina(madrina.getIdPersona());
            certificado.setIdPadrino(padrino.getIdPersona());
            certificado.setNombreCura(p.getApellidoCura()+" "+p.getNombreCura());
            
              certificado.setDomicilioPadres(txtDomPadres.getText());
        certificado.setCiudad(cmbCiudad.getSelectedItem().toString());
        certificado.setProvincia(cmbProvincia.getSelectedItem().toString());
        certificado.setFechaBautizmo(dtchFechaBautismo.getDate());
        certificado.setLibro(txtlibro.getText());
        certificado.setPartida(txtPartida.getText());
        certificado.setFolio(txtFolio.getText());
//        certificado.setNotasMarginales(txtareaMarginal.getText());

//        if (validacion()) {
//            JOptionPane.showMessageDialog(null, "Debe completar todos los campos...");
//        } else {
            // se creo un certificado nuevo
            if(modificar==false){
            certificadoDAO.insert(certificado);
            }else{
                // se cargo un certificado para actualizarlo
                certificadoDAO.update(certificado);
            }
            JOptionPane.showMessageDialog(null, "Se cargo correctamente...");
            activarBotonNuevo(false);
//        }
       
        
        
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos");
        }
      

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       
        //        parametros.put("fechaInicio",FechaUtil.getDateDD_MM_AAAA(fechaInicio.getDate()));
        //        parametros.put("fechaFin",FechaUtil.getDateDD_MM_AAAA(fechaFin.getDate()));
       
//       String logotipo="/images/iconTecnomatica.png";
      
       //parametros de entrada
       Map parametros = new HashMap();
       String logotipo="/images/1.jpg";
//       parametros.clear();
//       parametros.put("logoParroquia", this.getClass().getResourceAsStream(logotipo));
       
       
        ReporteCertificadoJRDataSource dataSource = new ReporteCertificadoJRDataSource();
        List<Certificado> lista = new ArrayList<Certificado>();
        lista.add(certificado);
        dataSource.setListCertificado(lista);
        JasperPrint jPrintt;
        JDialog reporte = new JDialog();
        reporte.setSize(900, 700);
        reporte.setLocationRelativeTo(null);
        reporte.setModal(true);
        reporte.setTitle("INFORME");
        //  JasperReport lreporte = (JasperReport) JRLoader.loadObject("reportes/reporteAsistencia.jasper");
        try {
            // jPrint = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reportes/reporteAsistencia.jasper"),null, new JRBeanCollectionDataSource(listaAs));
            jPrintt = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reporte/CertificadoParroquia.jasper"),(Map)parametros, dataSource);

            JRViewer jv = new JRViewer(jPrintt);
            reporte.getContentPane().add(jv);
            reporte.setVisible(true);

        } catch (JRException ex) {
///            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarVentana();
        
        // el indicador de modificar se pne en false ya que se creara un certificado nuevo
        modificar= false;
        // inicializar los botones de opciones
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnImprimir.setEnabled(false);
        btnBuscarCertificado.setEnabled(true);
        
        //mnuitm
        mnuItmNuevo.setEnabled(true);
        mnuItmGuardar.setEnabled(false);
        mnuItmImprimir.setEnabled(false);
        
        
              
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCertificadoActionPerformed
         
      // abre la ventana de busqueda 
        BusquedaCertificado bc = new BusquedaCertificado(certificado,this,true,txtNombPadrino,"padrino");
        bc.setVisible(true);
//        bc.setLocationRelativeTo(this);
//       
        // listar 
        if (bc.getCertificado()!=null) {
             // indicador de qeu se esta por cargar un certificado existente 
             modificar = true;
             // para que se pueda imprimir 
             btnImprimir.setEnabled(true);
             btnGuardar.setText("Actualizar");
             btnGuardar.setEnabled(true);
             
             //mnuItem
             mnuItmImprimir.setEnabled(true);
             mnuItmGuardar.setEnabled(true);
             mnuItmGuardar.setText("Actualizar");
            
            //llenar todos los campos de con los datosd del certificacdo}
            certificado= bc.getCertificado();
            tutor=new PersonaDAOImp().getPersona(certificado.getIdTutor());
            tutora= new PersonaDAOImp().getPersona(certificado.getIdTutora());
            padrino=new PersonaDAOImp().getPersona(certificado.getIdPadrino());
            madrina= new PersonaDAOImp().getPersona(certificado.getIdMadrina());
            ahijado= new PersonaDAOImp().getPersona(certificado.getIdAhijado());

      //datos de la configuarcion de la parroquia
     txtCura.setText(certificado.getNombreCura());
     txtCiudadParroquia.setText(p.getCiudadParroquia());
     txtNombreParroquia.setText(p.getNombreParroquia());
     
     //otros datos de certificado
     txtDNINiño.setText(ahijado.getDni());
     txtDomPadres.setText(certificado.getDomicilioPadres());
     txtFechNacimNiño.setText(FechaUtil.getDateDD_MM_AAAA(ahijado.getFechaNaciemiento()));
     txtFolio.setText(certificado.getFolio());
     txtLugarNacNiño.setText(ahijado.getLugarNacimiento());
     txtMadre.setText(tutora.getApellido()+" "+tutora.getNombre());
     txtNombMadrina.setText(madrina.getApellido()+" "+madrina.getNombre());
     txtNombNiño.setText(ahijado.getApellido()+" "+ahijado.getNombre());
     txtNombPadre.setText(tutor.getApellido()+" "+tutor.getNombre() );
     txtNombPadrino.setText(padrino.getApellido()+" "+padrino.getNombre());
     txtPartida.setText(certificado.getPartida());
//     txtareaMarginal.setText(certificado.getNotasMarginales());
     txtlibro.setText(certificado.getLibro());
     cmbCiudad.setSelectedItem("San Salvador de Jujuy");
     cmbProvincia.setSelectedItem("Jujuy");
     dtchFechaBautismo.setDate(certificado.getFechaBautizmo());
        }
    }//GEN-LAST:event_btnBuscarCertificadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       
        limpiarVentana();
        btnNuevo.setEnabled(false);
       btnGuardar.setText("Guardar");
       btnGuardar.setEnabled(true);
       
       btnImprimir.setEnabled(false);
       btnBuscarCertificado.setEnabled(true);
       
       //mnuItm
       mnuItmNuevo.setEnabled(false);
       mnuItmGuardar.setText("Guardar");
       mnuItmGuardar.setEnabled(true);
       mnuItmImprimir.setEnabled(false);
       
       
       modificar= false;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void mnuItemDatoParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDatoParroquiaActionPerformed
        Configuaracion config = new Configuaracion(this, true);
        limpiarVentana();
    }//GEN-LAST:event_mnuItemDatoParroquiaActionPerformed

    private void txtCiudadParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadParroquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadParroquiaActionPerformed

    private void txtlibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlibroKeyTyped
      consumirLetras(evt);
    }//GEN-LAST:event_txtlibroKeyTyped

    private void txtPartidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartidaKeyTyped
      consumirLetras(evt);
    }//GEN-LAST:event_txtPartidaKeyTyped

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        consumirLetras(evt);
    }//GEN-LAST:event_txtFolioKeyTyped

    private void txtNombPadrinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombPadrinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombPadrinoActionPerformed

    private void txtLugarNacNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarNacNiñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarNacNiñoActionPerformed

    private void mnuItmGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmGuardarActionPerformed
        btnGuardarActionPerformed(evt);
        
    }//GEN-LAST:event_mnuItmGuardarActionPerformed

    private void mnuItmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmNuevoActionPerformed

        btnNuevoActionPerformed(evt);
       
//       //mnuItm 
//       mnuItmNuevo.setEnabled(false);
//       mnuItmGuardar.setEnabled(true);
//       mnuItmImprimir.setEnabled(true);
//       mnuItmGuardar.setText("Guardar");
//       
//       
       
       modificar= false;
        
        
    }//GEN-LAST:event_mnuItmNuevoActionPerformed

    private void mnuItmImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmImprimirActionPerformed
    btnImprimirActionPerformed(evt);
    }//GEN-LAST:event_mnuItmImprimirActionPerformed

    private void mnuItmLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmLimpiarActionPerformed

        btnCancelarActionPerformed(evt);
       
    }//GEN-LAST:event_mnuItmLimpiarActionPerformed
  public void consumirLetras(java.awt.event.KeyEvent evt){
          // conusmir los caracteres del legajo excepto los numeros
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
  }
 
 public void activarBotonNuevo(boolean b){
     btnGuardar.setEnabled(b);
     btnImprimir.setEnabled(!b);
     btnNuevo.setEnabled(!b);
     
     // mnuItm tambien hacer lo mismo
     mnuItmGuardar.setEnabled(b);
     mnuItmImprimir.setEnabled(b);
     mnuItmNuevo.setEnabled(b);
     
 }
 public void limpiarVentana(){
     // Datos de Configuarcion . datos constantes
     p= new ParroquiaDaoImp().listarParroquia().get(0);
     txtCiudadParroquia.setText(p.getCiudadParroquia());
     txtCura.setText(p.getApellidoCura()+" "+p.getNombreCura());
     txtNombreParroquia.setText(p.getNombreParroquia());
     
     // datos del form
     txtDNINiño.setText("");
     txtDomPadres.setText("");
     txtFechNacimNiño.setText("");
     txtFolio.setText("");
     txtLugarNacNiño.setText("");
     txtMadre.setText("");
     txtNombMadrina.setText("");
     txtNombNiño.setText("");
     txtNombPadre.setText("");
     txtNombPadrino.setText("");
     txtPartida.setText("");
//     txtareaMarginal.setText("");
     txtlibro.setText("");
     cmbCiudad.setSelectedItem("San Salvador de Jujuy");
     cmbProvincia.setSelectedItem("Jujuy");
     dtchFechaBautismo.setDate(new Date());
 }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAgregarMadreCertficado;
    private javax.swing.JButton btnAgregarMadrinaCertficado;
    private javax.swing.JButton btnAgregarNiñoCertficado;
    private javax.swing.JButton btnAgregarPadreCertficado;
    private javax.swing.JButton btnAgregarPadrinoCertficado;
    private javax.swing.JButton btnBuscarCertificado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JMenuItem contentMenuItem;
    private com.toedter.calendar.JDateChooser dtchFechaBautismo;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenuItem mnuItemDatoParroquia;
    private javax.swing.JMenuItem mnuItmGuardar;
    private javax.swing.JMenuItem mnuItmImprimir;
    private javax.swing.JMenuItem mnuItmLimpiar;
    private javax.swing.JMenuItem mnuItmNuevo;
    private javax.swing.JMenuItem mnuItmSalir;
    private javax.swing.JTextField txtCiudadParroquia;
    private javax.swing.JTextField txtCura;
    private javax.swing.JTextField txtDNINiño;
    private javax.swing.JTextField txtDomPadres;
    private javax.swing.JTextField txtFechNacimNiño;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtLugarNacNiño;
    private javax.swing.JTextField txtMadre;
    private javax.swing.JTextField txtNombMadrina;
    public javax.swing.JTextField txtNombNiño;
    private javax.swing.JTextField txtNombPadre;
    private javax.swing.JTextField txtNombPadrino;
    private javax.swing.JTextField txtNombreParroquia;
    private javax.swing.JTextField txtPartida;
    private javax.swing.JTextField txtlibro;
    // End of variables declaration//GEN-END:variables
}
