/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.TextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelo.ModeloPersona;
import modelo.Persona;

/**
 *
 * @author dario
 */
public class BusquedaPersona extends javax.swing.JDialog {

    Persona persona;
    ModeloPersona modeloPersona = new ModeloPersona();
    private final TableRowSorter sorter;
    int numeroSeleccion;
    AltaCertificado parent;
    private final JTextField tipoPersona;
    private final String qPersonas;

    /**
     * Creates new form BusquedaPersona
     */
    public BusquedaPersona(Persona p, AltaCertificado parent, boolean modal, JTextField tipoPersona, String quePersona) {
        super(parent, modal);
        initComponents();
        //PersonaDAO personaDAO = new PersonaDAOImp();
        sorter = new TableRowSorter(modeloPersona);
        tblBusquedaPersona.setModel(modeloPersona);
        persona = p;
        //p.setNombre("DArio");
        this.parent = parent;//Estoy creando una variable global, le asigno el parent 
        this.tipoPersona = tipoPersona;//Estoy creando una variable global, le asigno el parent 
        //q traigo del anterior
        this.qPersonas = quePersona;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelarBusq = new javax.swing.JButton();
        btnActulizarDatosPersona = new javax.swing.JToggleButton();
        btnAgrePersCeritifcado = new javax.swing.JToggleButton();
        txtBusquedaDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaPersona = new javax.swing.JTable();
        btnAgregarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Certificado");
        setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Certificados por Persona", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setName(""); // NOI18N

        btnCancelarBusq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarBusq.setText("Cancelar");
        btnCancelarBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqActionPerformed(evt);
            }
        });

        btnActulizarDatosPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActulizarDatosPersona.setText("Actualizar Persona");
        btnActulizarDatosPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulizarDatosPersonaActionPerformed(evt);
            }
        });

        btnAgrePersCeritifcado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgrePersCeritifcado.setText("Agregar a Certificado");
        btnAgrePersCeritifcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrePersCeritifcadoActionPerformed(evt);
            }
        });

        txtBusquedaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaDNIKeyPressed(evt);
            }
        });

        tblBusquedaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBusquedaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusquedaPersona);

        btnAgregarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarPersona.setText("Agregar Persona");
        btnAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Busque Persona por Datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPersona)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActulizarDatosPersona)
                        .addGap(49, 49, 49)
                        .addComponent(btnCancelarBusq)
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel1)
                            .addGap(3, 3, 3)
                            .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btnAgrePersCeritifcado)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAgregarPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBusq)
                    .addComponent(btnActulizarDatosPersona))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addComponent(btnAgrePersCeritifcado)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 80, 560, 350);
        jPanel1.getAccessibleContext().setAccessibleName("Busqueda de Certificados  por Bautizado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("San Pedro y San Pablo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 480, 380, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Parroquia");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 460, 80, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spsp2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusquedaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaPersonaMouseClicked
//            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
//            persona = modeloPersona.getPersona(numeroSeleccion);
//            
////        this.parent.agregar(persona, tipoPersona,qPersonas);
////        this.dispose();
//        persona.setApellido(modeloPersona.getPersona(numeroSeleccion).getApellido());
//        persona.setNombre(modeloPersona.getPersona(numeroSeleccion).getNombre());
//        persona.setIdPersona(modeloPersona.getPersona(numeroSeleccion).getIdPersona());
    }//GEN-LAST:event_tblBusquedaPersonaMouseClicked

    private void txtBusquedaDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaDNIKeyPressed
        if (modeloPersona.getRowCount() != 0) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + txtBusquedaDNI.getText() + ".*"));
            tblBusquedaPersona.setRowSorter(sorter);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaDNIKeyPressed

    private void btnAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaActionPerformed
        AltaPersona at = new AltaPersona(parent, true, qPersonas);
        //        ActualizacionPersona at = new ActualizacionPersona(this, true);
        at.setVisible(true);
        at.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnAgregarPersonaActionPerformed

    private void btnAgrePersCeritifcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrePersCeritifcadoActionPerformed
        if (tblBusquedaPersona.getSelectedRow() != -1) {
            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
            persona = modeloPersona.getPersona(numeroSeleccion);
            this.parent.agregar(persona, tipoPersona, qPersonas);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_btnAgrePersCeritifcadoActionPerformed

    private void btnActulizarDatosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulizarDatosPersonaActionPerformed

        numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
        persona = modeloPersona.getPersona(numeroSeleccion);
        ActualizacionPersona actualizacionPersona = new ActualizacionPersona(this, true, persona, "actualizar");
        actualizacionPersona.setVisible(true);
//        actualizacionPersona = persona;
        //this.parent.agregar(persona, tipoPersona,qPersonas);
        this.dispose();
    }//GEN-LAST:event_btnActulizarDatosPersonaActionPerformed
//ACA SE LLAMA A LA VENTANA ELIMINAR
    //        numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
//        persona = modeloPersona.getPersona(numeroSeleccion);
//        ActualizacionPersona actualizacionPersona = new ActualizacionPersona(this, true, persona, "borrar");
//        actualizacionPersona.setVisible(true);
////        actualizacionPersona = persona;
//        //this.parent.agregar(persona, tipoPersona,qPersonas);
//        this.dispose();        // TODO add your handling code here:

    private void btnCancelarBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarBusqActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActulizarDatosPersona;
    private javax.swing.JToggleButton btnAgrePersCeritifcado;
    private javax.swing.JButton btnAgregarPersona;
    private javax.swing.JButton btnCancelarBusq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusquedaPersona;
    private javax.swing.JTextField txtBusquedaDNI;
    // End of variables declaration//GEN-END:variables
}
