/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modeloTable.ModeloAhijado;
import dominio.Persona;
import javax.swing.JTable;

/**
 *
 * @author dario
 */
public class BusquedaAhijado extends javax.swing.JDialog {

    private Persona persona;// variable auxiliar donde se almacenara la persona buscada
    ModeloAhijado modeloPersona ; // SE ENCARGA DE OBTENER LA LISTA DE PERSONAS PARA LA TABLA
    private  TableRowSorter sorter; 
    int numeroSeleccion;
    AltaCertificado parent;
    private boolean agregado = false;

    
    
    
    /**
     * Creates new form BusquedaAhijado
     */
    public BusquedaAhijado( AltaCertificado parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        
       
        inicializarTabla();
        this.parent = parent;//Estoy creando una variable global, le asigno el parent 
        //q traigo del anterior
        setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    public void inicializarTabla(){
        // inicializo la tabla busqueda
        modeloPersona = new ModeloAhijado();
        sorter = new TableRowSorter(modeloPersona);
        tblBusquedaPersona.setModel(modeloPersona); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelarBusq = new javax.swing.JButton();
        btnAgrePersCeritifcado = new javax.swing.JToggleButton();
        txtBusquedaDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaPersona = new javax.swing.JTable();
        btnAgregarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnActualizarPersona = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Certificado");
        setMaximumSize(new java.awt.Dimension(665, 440));
        setMinimumSize(new java.awt.Dimension(665, 440));
        setPreferredSize(new java.awt.Dimension(665, 440));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);

        btnCancelarBusq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarBusq.setText("Cancelar");
        btnCancelarBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqActionPerformed(evt);
            }
        });

        btnAgrePersCeritifcado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgrePersCeritifcado.setText("Agregar a Certificado");
        btnAgrePersCeritifcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrePersCeritifcadoActionPerformed(evt);
            }
        });

        txtBusquedaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaDNIKeyPressed(evt);
            }
        });

        tblBusquedaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBusquedaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusquedaPersona);

        btnAgregarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarPersona.setText("Nueva Persona");
        btnAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Filtrar persona:");

        btnActualizarPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizarPersona.setText("Actualizar Persona");
        btnActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPersonaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Busqueda por Persona");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnAgrePersCeritifcado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPersona)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarPersona)
                        .addGap(25, 25, 25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrePersCeritifcado)
                    .addComponent(btnCancelarBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 600, 350);
        jPanel1.getAccessibleContext().setAccessibleName("Busqueda de Certificados  por Bautizado");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosite.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 350, 80, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusquedaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaPersonaMouseClicked

    }//GEN-LAST:event_tblBusquedaPersonaMouseClicked

    private void txtBusquedaDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaDNIKeyPressed
        if (modeloPersona.getRowCount() != 0) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + txtBusquedaDNI.getText() + ".*"));
            tblBusquedaPersona.setRowSorter(sorter);
        }                
    }//GEN-LAST:event_txtBusquedaDNIKeyPressed

    private void btnAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaActionPerformed
        AltaAhijado at = new AltaAhijado(parent, true);
        // reflejar los cambios en la tabla
        if (at.isAgregado()) {
            // actualizar la tabla de persona
            inicializarTabla();
        }
    }//GEN-LAST:event_btnAgregarPersonaActionPerformed

    private void btnAgrePersCeritifcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrePersCeritifcadoActionPerformed
        setAgregado(true);
        if (tblBusquedaPersona.getSelectedRow() != -1) {
            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
            persona = modeloPersona.getPersona(numeroSeleccion);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_btnAgrePersCeritifcadoActionPerformed

    private void btnCancelarBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqActionPerformed
        setAgregado(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarBusqActionPerformed

    private void btnActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPersonaActionPerformed
           if (tblBusquedaPersona.getSelectedRow() != -1) {
            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
            persona = modeloPersona.getPersona(numeroSeleccion);
            // abrir el formulario alta de persona para editar los datos de persona
            AltaAhijado modificarPersona = new AltaAhijado(parent, true, persona);
            // actulizar la tabla con los datos modificados
               if (modificarPersona.isAgregado()) {
                  // si hubo modificacion en al Persona se actualiza la tabla
                   inicializarTabla();       
               }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_btnActualizarPersonaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPersona;
    private javax.swing.JToggleButton btnAgrePersCeritifcado;
    private javax.swing.JButton btnAgregarPersona;
    private javax.swing.JButton btnCancelarBusq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBusquedaPersona;
    private javax.swing.JTextField txtBusquedaDNI;
    // End of variables declaration//GEN-END:variables

    public Persona getPersona() {
        return persona;
    }

    public boolean isAgregado() {
        return agregado;
    }

    public void setAgregado(boolean agregado) {
        this.agregado = agregado;
    }
}
