/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.AltaCertificado;
import vista.AltaPersona;
import java.awt.TextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelo.Certificado;
import modelo.ModeloCertificado;
import modelo.ModeloPersona;
import modelo.Persona;


/**
 *
 * @author dario
 */
public class BusquedaCertificado extends javax.swing.JDialog {

    Certificado certificado;
    ModeloCertificado modeloCertificado = new ModeloCertificado();
    private final TableRowSorter sorter;
    int numeroSeleccion;
    AltaCertificado parent;
    private final JTextField tipoPersona;
    private final String qPersonas;
    
    public Certificado getCertificado() {
        return certificado;
    }

    public void setCertificado(Certificado certificado) {
        this.certificado = certificado;
    }

    /**
     * Creates new form BusquedaPersona
     */
    public BusquedaCertificado(Certificado certificado, AltaCertificado parent, boolean modal, JTextField tipoPersona, String quePersona) {
        super(parent, modal);
        initComponents();
        
        sorter = new TableRowSorter(modeloCertificado);
        tblBusquedaCertificado.setModel(modeloCertificado);
        this.parent = parent;//Estoy creando una variable global, le asigno el parent 
        this.tipoPersona = tipoPersona;//Estoy creando una variable global, le asigno el parent 
        //q traigo del anterior
        this.qPersonas = quePersona;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaNumCertificado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaCertificado = new javax.swing.JTable();
        btnCancelarBusq = new javax.swing.JButton();
        btnAgrePersCeritifcado = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 440));
        setMinimumSize(new java.awt.Dimension(650, 440));
        setPreferredSize(new java.awt.Dimension(650, 440));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Certificados", 0, 0, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setText("Busque el Certificado por Datos:");

        txtBusquedaNumCertificado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaNumCertificadoKeyPressed(evt);
            }
        });

        tblBusquedaCertificado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBusquedaCertificado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaCertificadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusquedaCertificado);

        btnCancelarBusq.setText("Cancelar");
        btnCancelarBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqActionPerformed(evt);
            }
        });

        btnAgrePersCeritifcado.setText("Agregar a Certificado");
        btnAgrePersCeritifcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrePersCeritifcadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusquedaNumCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnAgrePersCeritifcado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnCancelarBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(247, 247, 247))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusquedaNumCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrePersCeritifcado)
                    .addComponent(btnCancelarBusq))
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 600, 290);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logosite.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 350, 80, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusquedaCertificadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaCertificadoMouseClicked

    }//GEN-LAST:event_tblBusquedaCertificadoMouseClicked

    private void txtBusquedaNumCertificadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaNumCertificadoKeyPressed
        if (modeloCertificado.getRowCount() != 0) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + txtBusquedaNumCertificado.getText() + ".*"));
            tblBusquedaCertificado.setRowSorter(sorter);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaNumCertificadoKeyPressed

    private void btnAgrePersCeritifcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrePersCeritifcadoActionPerformed
        if (tblBusquedaCertificado.getSelectedRow() != -1) {
            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaCertificado.getSelectedRow());
            // agrego al certificado
            setCertificado(modeloCertificado.getCertificado(numeroSeleccion));
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_btnAgrePersCeritifcadoActionPerformed

    private void btnCancelarBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarBusqActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgrePersCeritifcado;
    private javax.swing.JButton btnCancelarBusq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusquedaCertificado;
    private javax.swing.JTextField txtBusquedaNumCertificado;
    // End of variables declaration//GEN-END:variables
}
