/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.ActualizacionCertificado;
import java.awt.TextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelo.ModeloPersona;
import modelo.Persona;

/**
 *
 * @author dario
 */
public class PersonaEditadaCertificado extends javax.swing.JDialog {

    Persona persona;
    ModeloPersona modeloPersona = new ModeloPersona();
    private final TableRowSorter sorter;
    int numeroSeleccion;
    ActualizacionCertificado parent;
    private final JTextField tipoPersona;
    private final String qPersonas;

    /**
     * Creates new form BusquedaPersona
     */
    public PersonaEditadaCertificado(ActualizacionCertificado parent, boolean modal, JTextField tipoPersona, String quePersona) {
        super(parent, modal);
        initComponents();
        //PersonaDAO personaDAO = new PersonaDAOImp();
        sorter = new TableRowSorter(modeloPersona);
        tblBusquedaPersona.setModel(modeloPersona);
      //  persona = p;
        //p.setNombre("DArio");
        this.parent = parent;//Estoy creando una variable global, le asigno el parent 
        this.tipoPersona = tipoPersona;//Estoy creando una variable global, le asigno el parent 
        //q traigo del anterior
        this.qPersonas = quePersona;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaPersona = new javax.swing.JTable();
        txtBusquedaDNI = new javax.swing.JTextField();
        btnAgrePersCeritifcado = new javax.swing.JToggleButton();
        btnCancelarBusq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Busque Persona por Datos");

        tblBusquedaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBusquedaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusquedaPersona);

        txtBusquedaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaDNIKeyPressed(evt);
            }
        });

        btnAgrePersCeritifcado.setText("Agregar a Certificado");
        btnAgrePersCeritifcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrePersCeritifcadoActionPerformed(evt);
            }
        });

        btnCancelarBusq.setText("Cancelar");
        btnCancelarBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 272, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAgrePersCeritifcado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarBusq)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgrePersCeritifcado)
                    .addComponent(btnCancelarBusq))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusquedaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaPersonaMouseClicked
//            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
//            persona = modeloPersona.getPersona(numeroSeleccion);
//            
////        this.parent.agregar(persona, tipoPersona,qPersonas);
////        this.dispose();
//        persona.setApellido(modeloPersona.getPersona(numeroSeleccion).getApellido());
//        persona.setNombre(modeloPersona.getPersona(numeroSeleccion).getNombre());
//        persona.setIdPersona(modeloPersona.getPersona(numeroSeleccion).getIdPersona());
    }//GEN-LAST:event_tblBusquedaPersonaMouseClicked

    private void txtBusquedaDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaDNIKeyPressed
        if (modeloPersona.getRowCount() != 0) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + txtBusquedaDNI.getText() + ".*"));
            tblBusquedaPersona.setRowSorter(sorter);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaDNIKeyPressed

    private void btnAgrePersCeritifcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrePersCeritifcadoActionPerformed
        if (tblBusquedaPersona.getSelectedRow() != -1) {
            numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
            persona = modeloPersona.getPersona(numeroSeleccion);
            this.parent.agregar(persona, qPersonas);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_btnAgrePersCeritifcadoActionPerformed
//ACA SE LLAMA A LA VENTANA ELIMINAR
    //        numeroSeleccion = sorter.convertRowIndexToModel(tblBusquedaPersona.getSelectedRow());
//        persona = modeloPersona.getPersona(numeroSeleccion);
//        ActualizacionPersona actualizacionPersona = new ActualizacionPersona(this, true, persona, "borrar");
//        actualizacionPersona.setVisible(true);
////        actualizacionPersona = persona;
//        //this.parent.agregar(persona, tipoPersona,qPersonas);
//        this.dispose();        // TODO add your handling code here:

    private void btnCancelarBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarBusqActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgrePersCeritifcado;
    private javax.swing.JButton btnCancelarBusq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusquedaPersona;
    private javax.swing.JTextField txtBusquedaDNI;
    // End of variables declaration//GEN-END:variables
}
