package modelo;
// Generated 22/07/2013 17:32:59 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Certificado generated by hbm2java
 */
public class Certificado  implements java.io.Serializable {


     private Integer numeroCertificado;
     private int idCura;
     private Integer idAhijado;
     private Integer idTutora;
     private Integer idTutor;
     private Integer idMadrina;
     private Integer idPadrino;
     private String nombreParroquia;
     private String domicilioParooquia;
     private String telefParroquia;
     private String barrioParroquia;
     private String libro;
     private String folio;
     private String partida;
     private Date fechaBautizmo;
     private String domicilioPadres;
     private String notasMarginales;
     private String ciudad;
     private String provincia;

    public Certificado() {
    }

	
    public Certificado(int idCura) {
        this.idCura = idCura;
    }
    public Certificado(int idCura, Integer idAhijado, Integer idTutora, Integer idTutor, Integer idMadrina, Integer idPadrino, String nombreParroquia, String domicilioParooquia, String telefParroquia, String barrioParroquia, String libro, String folio, String partida, Date fechaBautizmo, String domicilioPadres, String notasMarginales, String ciudad, String provincia) {
       this.idCura = idCura;
       this.idAhijado = idAhijado;
       this.idTutora = idTutora;
       this.idTutor = idTutor;
       this.idMadrina = idMadrina;
       this.idPadrino = idPadrino;
       this.nombreParroquia = nombreParroquia;
       this.domicilioParooquia = domicilioParooquia;
       this.telefParroquia = telefParroquia;
       this.barrioParroquia = barrioParroquia;
       this.libro = libro;
       this.folio = folio;
       this.partida = partida;
       this.fechaBautizmo = fechaBautizmo;
       this.domicilioPadres = domicilioPadres;
       this.notasMarginales = notasMarginales;
       this.ciudad = ciudad;
       this.provincia = provincia;
    }
   
    public Integer getNumeroCertificado() {
        return this.numeroCertificado;
    }
    
    public void setNumeroCertificado(Integer numeroCertificado) {
        this.numeroCertificado = numeroCertificado;
    }
    public int getIdCura() {
        return this.idCura;
    }
    
    public void setIdCura(int idCura) {
        this.idCura = idCura;
    }
    public Integer getIdAhijado() {
        return this.idAhijado;
    }
    
    public void setIdAhijado(Integer idAhijado) {
        this.idAhijado = idAhijado;
    }
    public Integer getIdTutora() {
        return this.idTutora;
    }
    
    public void setIdTutora(Integer idTutora) {
        this.idTutora = idTutora;
    }
    public Integer getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(Integer idTutor) {
        this.idTutor = idTutor;
    }
    public Integer getIdMadrina() {
        return this.idMadrina;
    }
    
    public void setIdMadrina(Integer idMadrina) {
        this.idMadrina = idMadrina;
    }
    public Integer getIdPadrino() {
        return this.idPadrino;
    }
    
    public void setIdPadrino(Integer idPadrino) {
        this.idPadrino = idPadrino;
    }
    public String getNombreParroquia() {
        return this.nombreParroquia;
    }
    
    public void setNombreParroquia(String nombreParroquia) {
        this.nombreParroquia = nombreParroquia;
    }
    public String getDomicilioParooquia() {
        return this.domicilioParooquia;
    }
    
    public void setDomicilioParooquia(String domicilioParooquia) {
        this.domicilioParooquia = domicilioParooquia;
    }
    public String getTelefParroquia() {
        return this.telefParroquia;
    }
    
    public void setTelefParroquia(String telefParroquia) {
        this.telefParroquia = telefParroquia;
    }
    public String getBarrioParroquia() {
        return this.barrioParroquia;
    }
    
    public void setBarrioParroquia(String barrioParroquia) {
        this.barrioParroquia = barrioParroquia;
    }
    public String getLibro() {
        return this.libro;
    }
    
    public void setLibro(String libro) {
        this.libro = libro;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }
    public Date getFechaBautizmo() {
        return this.fechaBautizmo;
    }
    
    public void setFechaBautizmo(Date fechaBautizmo) {
        this.fechaBautizmo = fechaBautizmo;
    }
    public String getDomicilioPadres() {
        return this.domicilioPadres;
    }
    
    public void setDomicilioPadres(String domicilioPadres) {
        this.domicilioPadres = domicilioPadres;
    }
    public String getNotasMarginales() {
        return this.notasMarginales;
    }
    
    public void setNotasMarginales(String notasMarginales) {
        this.notasMarginales = notasMarginales;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


