package modelo;
// Generated 04/08/2013 12:46:07 by Hibernate Tools 3.2.1.GA



/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private Integer idParroquia;
     private String nombreParroquia;
     private String apellidoCura;
     private String nombreCura;
     private String ciudadParroquia;

    public Parroquia() {
    }

	
    public Parroquia(String nombreParroquia) {
        this.nombreParroquia = nombreParroquia;
    }
    public Parroquia(String nombreParroquia, String apellidoCura, String nombreCura, String ciudadParroquia) {
       this.nombreParroquia = nombreParroquia;
       this.apellidoCura = apellidoCura;
       this.nombreCura = nombreCura;
       this.ciudadParroquia = ciudadParroquia;
    }
   
    public Integer getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(Integer idParroquia) {
        this.idParroquia = idParroquia;
    }
    public String getNombreParroquia() {
        return this.nombreParroquia;
    }
    
    public void setNombreParroquia(String nombreParroquia) {
        this.nombreParroquia = nombreParroquia;
    }
    public String getApellidoCura() {
        return this.apellidoCura;
    }
    
    public void setApellidoCura(String apellidoCura) {
        this.apellidoCura = apellidoCura;
    }
    public String getNombreCura() {
        return this.nombreCura;
    }
    
    public void setNombreCura(String nombreCura) {
        this.nombreCura = nombreCura;
    }
    public String getCiudadParroquia() {
        return this.ciudadParroquia;
    }
    
    public void setCiudadParroquia(String ciudadParroquia) {
        this.ciudadParroquia = ciudadParroquia;
    }




}


